### PR TITLE
Fix Update datetime field for sqlsrv

### PR DESCRIPTION
**Pull request by pierre-H**
https://github.com/doctrine/dbal/issues/949

### CODE REVIEW

**Comment by billschaller** [comment]
This is not a fix, there are no tests, and it will break existing behavior because of time zone issues...

**Comment by Ocramius** [comment]
Closing as per @billschaller's review

**Review by billschaller — COMMENTED** [review]
AFAIK because this doesn't specify the timezone parameter for this time format, SQL Server will fill it with +00:00, breaking existing behavior. Provide a test suite ensuring behavior is consistent before and after and this would be a safe merge. Otherwise no.

**Comment by pierre-H** [comment]
@billschaller I just used this solution : https://www.fusonic.net/en/blog/php-datetime-and-mssql/ because I had this same problem.
 I don't know exactly what do you need : a code which use that ?

**Comment by billschaller** [comment]
pierre-H - at a bare minimum we need a failing test to demonstrate the error you're seeing. The error you're experiencing would show up if you were using datetime columns instead of datetime2. Can you post a gist of the entity and a schema dump of the table in the database you're trying to access?

**Comment by billschaller** [comment]
@pierre-H - at a bare minimum we need a failing test to demonstrate the error you're seeing. The error you're experiencing would show up if you were using datetime columns instead of datetime2. Can you post a gist of the entity and a schema dump of the table in the database you're trying to access?

**Comment by pierre-H** [comment]
This isn't needed anymore.
See https://github.com/doctrine/dbal/issues/949#issuecomment-285123074

**Pull request closed without merging**
