### PR TITLE
Remove ExpressionBuilder::andX()/orX()

### PR DESCRIPTION
**Pull request by BenMorel**
Continuing the work started in #3851, this time on `master`.

### CODE REVIEW

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @BenMorel!

**Comment by BenMorel** [comment]
Thanks! Could you please let me know when you merge it to `master`, so that I can continue the work there and to fix #3845?

**Comment by morozov** [comment]
@BenMorel you mean merge this PR into `master`? It's already merged.

**Comment by BenMorel** [comment]
Sorry, I left the comment on the wrong PR. I meant to write it on #3864.

**Comment by morozov** [comment]
Just filed #3866.

**Pull request merged**
