### PR TITLE
ref #2586 Fix function getCurrentDateSql() for SQL Server 2008 and above

### PR DESCRIPTION
**Pull request by cgardiennet**
Fix done. Up to you.

### CODE REVIEW

**Comment by Ocramius** [comment]
Linking #2586

**Comment by billschaller** [comment]
Seems silly to test this

**Comment by cgardiennet** [comment]
@billschaller : what can i do to help to test ? For me it's working.

**Comment by cgardiennet** [comment]
@Ocramius : same process here ?
https://github.com/doctrine/dbal/blob/master/tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php

**Comment by Ocramius** [comment]
Yep, same process

**Comment by morozov** [comment]
Closing as stale and missing tests.

**Pull request closed without merging**
