### PR TITLE
Typo: behavior -> behaviour

### PR DESCRIPTION
**Pull request by noplanman**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | little typo

#### Summary

Typo fixed: `behavior` -> `behaviour`

### CODE REVIEW

**Review by lcobucci — COMMENTED** [review]
I think we're using the American spelling for our docs, right @morozov?

**Comment by morozov** [comment]
I don't think we should be accepting such changes w/o having a publicly available standard and we don't have one AFAIK. Personally, I'd be in favor (without the _u_) of the American spelling.

**Comment by noplanman** [comment]
Ok, no problem. Was just adapting to what was being used in other places already.

**Comment by SenseException** [comment]
Those are a lot of commits for fixing a typo. Is there a base branch mismatch?

**Pull request closed without merging**
