### PR TITLE
Strong type $sql param in logger interfaces

### PR DESCRIPTION
**Pull request by mvorisek**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no - LSP not violated by declaring stricter iface
| Fixed issues | no

### CODE REVIEW

**Comment by greg0ire** [comment]
If #4386 gets merged, this will be a BC-break because PHP 7.1 does not support dropping type declarations when extending a class.

**Comment by mvorisek** [comment]
> 
> 
> If #4386 gets merged, this will be a BC-break because PHP 7.1 does not support dropping type declarations when extending a class.

That is correct - https://3v4l.org/Asimv - one small reason to never reintroduce PHP 7.1 support

**Comment by mvorisek** [comment]
I belive we can merge this, if PHP 7.1 support will be reintroduced, than this change (and every other needed) will be reverted in that PR for 2.x

**Comment by greg0ire** [comment]
We could, but probably won't in order to not make this harder than it should be. I expect the PR to be either merged or rejected in a reasonable time frame, we can decide what should happen to this PR after, there is absolutely no rush.

**Comment by morozov** [comment]
Strict scalar types are already implemented for the entire codebase in `master`. Implementing them in `2.x` would be a breaking change, regardless of the supported PHP versions.

**Comment by mvorisek** [comment]
@morozov in master yes, in 3.x no - what is the difference between these branches, is master planned for 4.x and when will it be roughly released? Thanks.

**Comment by greg0ire** [comment]
Yes `master` is currently 4.x, we cannot promise that everything that is on master will be released in 4.0.0 though (we originally planned to release it as 3.0.0).

**Pull request closed without merging**
