### PR TITLE
Test for appveyor.

### PR DESCRIPTION
**Pull request by jwage**
|      Q       |   A
|------------- | -----------
| Type         | bug/feature/improvement
| BC Break     | yes/no
| Fixed issues |

### CODE REVIEW

**Comment by SenseException** [comment]
WIP?

**Comment by jwage** [comment]
Testing appveyor. It isn't working currently. Trying to get it working again.

**Comment by morozov** [comment]
Could be also reused as a test for Travis :thinking: (seems like it's consistently failing for a couple of days).

**Comment by jwage** [comment]
👍

**Comment by morozov** [comment]
The build is green. Closing.

**Pull request closed without merging**
