### PR TITLE
Fixes from PHPStan l1 for tests

### PR DESCRIPTION
**Pull request by carusogabriel**
Waiting for #3025, but not ready to enable PHPStan at `tests/` yet.

### CODE REVIEW

**Comment by Ocramius** [comment]
Some unrelated CS issues were found here: unsure if worth fixing or better to just merge and let `diffcs` shut up with the next PR.

**Comment by carusogabriel** [comment]
@Ocramius Is up to you :)

I’d love to start fix CS in dbal, but @Majkl578 asked to wait before development ends, so 👍🏻 for merge this and fix CS in the future

**Comment by Ocramius** [comment]
@carusogabriel as long as it doesn't break other PRs

**Comment by carusogabriel** [comment]
Can we merge this one with only one small CS violation?

**Review by Ocramius — APPROVED** [review]
Yep!

**Pull request merged**
