### PR TITLE
Remove test that covers OCI8 classes

### PR DESCRIPTION
**Pull request by greg0ire**
This should result in a coverage drop.

### CODE REVIEW

**Comment by greg0ire** [comment]
… and results in a coverage increase :facepalm:

**Comment by greg0ire** [comment]
And I think that somehow has to do with AppVeyor / SqlSrv

**Comment by morozov** [comment]
> And I think that somehow has to do with AppVeyor / SqlSrv

Why do you think so? Maybe try to disable coverage submission from there?

**Comment by greg0ire** [comment]
> Why do you think so? Maybe try to disable coverage submission from there?

I think so because of the files that appear in the diff.

Also, I think the issue might be a lack of reports for merge commits, but I'm not sure, because I see those for a6fe19ee668e6be3bc4c20794a4b616454f3e38a, here: https://codecov.io/gh/doctrine/dbal/commit/a6fe19ee668e6be3bc4c20794a4b616454f3e38a/build (and I don't see any from GH, by the way, only from AppVeyor and Travis :sweat_smile: )

**Comment by greg0ire** [comment]
What's quite odd, is when I browse the url that appears in the GH checks, I land here: https://codecov.io/gh/doctrine/dbal/commit/7c3efc9ffbad51e7ac097bc82c195817be2fc24f/build

It says "Commit was deleted by force push or pull request rebase. ", which was never the case. That commit hash is not the hash of my commit, so it's probably the hash of a commit that is the result of a (forced even fast-forward) merge between the target and the base

**Comment by morozov** [comment]
> That commit hash is not the hash of my commit, so it's probably the hash of a commit that is the result of a (forced even fast-forward) merge between the target and the base.

A CI doing a merge before the build is acceptable because this is what eventually is going to happen to the commit being built. But it shouldn't result in any deletion of a commit.

**Comment by greg0ire** [comment]
I can find a reference to 7c3efc9 in the Travis build, so it builds that same commit too… but for some reason the CodeCov tool does not send post its reports to the same url on both systems.

**Comment by greg0ire** [comment]
I think the issue resides with the super-shallow cloning we perform here: https://github.com/doctrine/dbal/pull/4180/checks?check_run_id=899598863#step:3:30

**Comment by greg0ire** [comment]
The url in the checks looks good now…, and the interesting lines appears too: https://github.com/doctrine/dbal/pull/4180/checks?check_run_id=899854658#step:8:16 

I don't fully understand why though, because `git show` is in use here, and a commit is supposed to contain the hash of its parents?

**Comment by greg0ire** [comment]
Handled in #4181, I will rebase that one afterwards to see if we get results we understand.

**Comment by greg0ire** [comment]
@morozov results are still surprising… I think that's because of a lack of reports from GH for merge commits: https://codecov.io/gh/doctrine/dbal/src/34b1893ea1e0b2138a6aa7e169b9b84a672a537e/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php

Maybe it's because of this line?

https://github.com/doctrine/dbal/blob/34b1893ea1e0b2138a6aa7e169b9b84a672a537e/.github/workflows/continuous-integration.yml#L5

**Comment by greg0ire** [comment]
This confirms my hypothesis: https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/2

**Comment by greg0ire** [comment]
+-0.04% is a better result, but still not what I expected… I mean why is it not just -0.04%? Maybe -0.04% happens when you add uncovered code?

The source code and the graph look good though, it's as documented: https://docs.codecov.io/docs/viewing-source-code#line-coverage-changes

**Comment by morozov** [comment]
It looks like a bug in Codecov updating the build status. The [report](https://codecov.io/gh/doctrine/dbal/compare/93664d0c68e28769da8d1ddc2e6746394b18a374...a91bbf0ba8039edfe27f49257e9d5d9973a5d20b) clearly states that it's -0.04%.

**Comment by greg0ire** [comment]
Cc @thomasrockhu I would love to have your input on this

**Comment by greg0ire** [comment]
Reopening since otherwise you can't see the checks :sweat_smile:

**Comment by greg0ire** [comment]
Aaaaand now it's +0.07% :facepalm:

**Comment by morozov** [comment]
So it looks like the failed parent build set a lower code coverage bar which this PR exceeded even with some tests removed?

This inconsistency is really concerning. We can either add some retries to fetching the script (it would have to be done separately for AppVeyor and Travis) or we can fail the build if the submission fails so that we at least could restart it manually.

**Comment by morozov** [comment]
[Another one](https://travis-ci.org/github/doctrine/dbal/jobs/711245228):
> $ bash <(curl -s https://codecov.io/bash)
> curl: (7) Failed to connect to codecov.io port 443: Connection timed out

**Comment by greg0ire** [comment]
> we can fail the build if the submission fails so that we at least could restart it manually.

That's what currently happens on AppVeyor, but maybe you were referring to other CI platforms?

**Comment by greg0ire** [comment]
Apparently there was an issue with uploads 2 days ago, maybe it's not 100% resolved? See https://status.codecov.io/

**Comment by greg0ire** [comment]
I reported the issue here: https://community.codecov.io/t/frequent-upload-failures/1793

**Comment by morozov** [comment]
> That's what currently happens on AppVeyor, but maybe you were referring to other CI platforms?

Yes, I was talking about Travis. See https://github.com/doctrine/dbal/pull/4180#issuecomment-663243195.

For the reference, the script itself [handles](https://travis-ci.org/github/doctrine/dbal/jobs/711245228) the upload failures:
```
->  Pinging Codecov
https://codecov.io/upload/v4?package=bash-20200707-353aa93&token=secret&branch=3.0.x&commit=824d2eb0af416006f8a5317d08882ea204f608f9&build=9733.21&build_url=&name=&tag=&slug=doctrine%2Fdbal&service=travis&flags=&pr=4187&job=711245228&cmd_args=
->  Uploading to
curl: (3) <url> malformed
    X> Failed to upload
    -> Sleeping for 30s and trying again...
->  Pinging Codecov
https://codecov.io/upload/v4?package=bash-20200707-353aa93&token=secret&branch=3.0.x&commit=824d2eb0af416006f8a5317d08882ea204f608f9&build=9733.21&build_url=&name=&tag=&slug=doctrine%2Fdbal&service=travis&flags=&pr=4187&job=711245228&cmd_args=
->  Uploading to
https://storage.googleapis.com/codecov/v4/raw/2020-07-23/08D93337797922BBA4BC74202C117709/824d2eb0af416006f8a5317d08882ea204f608f9/26fa9450-dfaf-4c5a-9bf2-4ecf8fe01403.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=GOOG1EQX6OZVJGHKK3633AAFGLBUCOOATRACRQRQF6HMSMLYUP6EAD6XSWAAY%2F20200723%2FUS%2Fs3%2Faws4_request&X-Amz-Date=20200723T214301Z&X-Amz-Expires=10&X-Amz-SignedHeaders=host&X-Amz-Signature=f2f01e9aeac03498908c4d94ec42e8e73fa6d7f7d99bcc537053fe3409c7d52a
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82319    0     0  100 82319      0   472k --:--:-- --:--:-- --:--:--  472k
    -> View reports at https://codecov.io/github/doctrine/dbal/commit/824d2eb0af416006f8a5317d08882ea204f608f9
```

**Comment by thomasrockhu** [comment]
Hi @greg0ire, I'll take a look at the increase to code coverage, but yes, we are aware of this issue and are making some changes in the next sprint or two to get some consistency. I would suggest retrying the call to pull the bash script.

**Comment by greg0ire** [comment]
Oh right there are 2 issues, one when using `curl`, one when using the bash uploader, we can definitely mitigate the `curl` one with the right options

**Comment by thomasrockhu** [comment]
Hi @greg0ire, I did a little digging and I noticed something strange.

I took a look at the [changes](https://codecov.io/gh/doctrine/dbal/pull/4180/changes) and focused on `Dumper.php`. Looking at the [builds](https://codecov.io/gh/doctrine/dbal/commit/a91bbf0ba8039edfe27f49257e9d5d9973a5d20b/build) for this PR, I noticed the build labelled `5wiga2ir5kqao80p` is reporting coverage on weird lines
```
 <file name="C:\projects\dbal\lib\Doctrine\DBAL\Tools\Dumper.php">
        <class name="Doctrine\DBAL\Tools\Dumper" namespace="Doctrine\DBAL\Tools">
          <metrics complexity="22" methods="4" coveredmethods="1" conditionals="0" coveredconditionals="0" statements="51" coveredstatements="43" elements="55" coveredelements="44"/>
        </class>
        <line num="58" type="method" name="dump" visibility="public" complexity="2" crap="2.01" count="3"/>
        <line num="60" type="stmt" count="3"/>
        <line num="63" type="stmt" count="3"/>
        <line num="64" type="stmt" count="0"/>
        <line num="67" type="stmt" count="3"/>
        <line num="69" type="stmt" count="3"/>
        <line num="70" type="stmt" count="3"/>
        <line num="73" type="stmt" count="3"/>
        <line num="76" type="stmt" count="3"/>
        <line num="78" type="stmt" count="3"/>
        <line num="87" type="method" name="export" visibility="public" complexity="12" crap="12.20" count="12"/>
        <line num="89" type="stmt" count="12"/>
        <line num="90" type="stmt" count="12"/>
        <line num="92" type="stmt" count="12"/>
        <line num="93" type="stmt" count="0"/>
        <line num="96" type="stmt" count="12"/>
        <line num="97" type="stmt" count="2"/>
        <line num="98" type="stmt" count="2"/>
        <line num="101" type="stmt" count="12"/>
        <line num="102" type="stmt" count="4"/>
        <line num="104" type="stmt" count="4"/>
        <line num="105" type="stmt" count="4"/>
        <line num="108" type="stmt" count="4"/>
        <line num="111" type="stmt" count="12"/>
```

You can see this line up with the coverage we are showing.

**Comment by greg0ire** [comment]
Thanks for the analysis @thomasrockhu ! I see that the same lines (for instance line 60) appear in a report for 2.10.x : https://codecov.io/api/gh/doctrine/dbal/download/build?path=v4/raw/2020-07-25/08D93337797922BBA4BC74202C117709/217b2cf9684313e4e818f7ee2ffab7889bf63974/291bb7aa-1488-4c89-af45-83c4fb01a6e0.txt
And that's in fact true of all the builds I had a look at for 2.10.x

**Comment by morozov** [comment]
@greg0ire do you plan to work more on this?

**Comment by greg0ire** [comment]
I don't think I will, let's close this.

**Pull request closed without merging**
