### PR TITLE
added badges for continuousphp and other badges for 2.6

### PR DESCRIPTION
**Pull request by ppaulis**
This PR completes the README with badges for the 2.6 branch and also adds the badges from continuousphp.

### CODE REVIEW

**Comment by Ocramius** [comment]
@ppaulis those look extremely bulky! Is there a way to make some that work through shields.io or such?

**Comment by ppaulis** [comment]
@Ocramius I started working on shields.io-integration :-), I'll keep you updated as soon as we are good there.

**Comment by ppaulis** [comment]
@Ocramius waiting now for the shields.io-PR to be merged:
badges/shields/pull/1051

**Comment by Ocramius** [comment]
@ppaulis thanks! :+1:

**Comment by ppaulis** [comment]
@Ocramius replaced the custom badges with badges from shields.io :-)

**Review by lcobucci — APPROVED** [review]

**Comment by lcobucci** [comment]
@ppaulis 🚢 thanks for your contribution!

**Pull request merged**
