### PR TITLE
Try removing quotes

### PR DESCRIPTION
**Pull request by greg0ire**
[I have been told](https://github.com/codecov/codecov-action/issues/1487#issuecomment-2286955193) it could fix the issue we have with Codecov. Let us try the suggestion before reporting a new issue.

### CODE REVIEW

**Comment by derrabus** [comment]
If that works: Please target 3.9.x.

**Comment by greg0ire** [comment]
OK. FTR I'm not very hopeful it will fix the issue, but I've been wrong before.

**Comment by greg0ire** [comment]
:exploding_head: :exploding_head: :exploding_head: why does it work?!?

I'm rebasing.

**Review by derrabus — APPROVED** [review]

**Comment by greg0ire** [comment]
It seems that it still fails, it's just that it fails randomly: https://github.com/doctrine/dbal/actions/runs/10426300024/job/28890873426?pr=5897

I will open another ticket on Codecov

EDIT: https://github.com/codecov/codecov-action/issues/1548

**Pull request merged**
