### PR TITLE
Deprecated dbal:import CLI command

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | deprecation
| BC Break     | no
| Fixed issues | #3237

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
:+1:

**Comment by lcobucci** [comment]
@Ocramius @morozov in some places we're using `@deprecated` + `@trigger_error()` in others just `@deprecated` to handle deprecations, which way is the one to go?

**Comment by Ocramius** [comment]
To be honest, I don't know. The entire situation with requiring an additional component to run tests with deprecated bits of code is extremely confusing, IMO, so the silent deprecation approach isn't any better eithe.

**Comment by lcobucci** [comment]
@Ocramius I agree, I really dislike this whole phpunit-bridge stuff and I think that https://github.com/phpstan/phpstan-deprecation-rules is the appropriated tool to check for deprecations. 

This means that I believe that we could make a call and standardise things in the repos.... shall we move this discussion to gitter?

**Comment by Ocramius** [comment]
I'd be on board with using @phpstan's approach: simpler and checks only the sources, which is exactly what we want.

Yes, that means that many users won't see anything until we remove a feature, but the silenced operation is just a mess.

**Comment by morozov** [comment]
@lcobucci, @Ocramius, I'm with you.

**Pull request merged**
