### PR TITLE
Merge 2.13.x into 3.1.x

### PR DESCRIPTION
**Pull request by derrabus**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | N/A

### CODE REVIEW

**Comment by derrabus** [comment]
I don't know how to merge up #4638 properly since the directory structure inside the tests folder has changed.

cc @Ocramius

**Comment by Ocramius** [comment]
Test dirs were added AFAIK: everything else should (in theory) have been
handled by `git mv`

**Comment by derrabus** [comment]
In your PR, you've added a file `tests/Doctrine/StaticAnalysis/DBAL/driver-manager-retrieves-correct-connection-type.php`. In 3.0, the unit tests have been moved from `tests/Doctrine/Tests` to `tests`. That new file of yours felt a bit misplaced inside the `tests` folder now, so I've moved it into the `ci` folder.

**Comment by greg0ire** [comment]
:thinking: I think `tests` would have been better actually… `ci` is for files that will only ever be useful in the CI, isn't it @morozov ? Maybe there should be a new directory called `static-analysis` or `sa`?

**Comment by derrabus** [comment]
I don't have strong opinions here. Just tell me where to move that file. 🙂 

Alternatively, this could be done in a follow-up after the merge.

**Comment by greg0ire** [comment]
Since the file is not suffixed with `Test`, it will not be picked up by PHPUnit. I think you can simply move them back to `tests`, and then in a follow-up we can rework the directory structure.

**Comment by derrabus** [comment]
Yeah, but CodeSniffer will pick it up and complain when I move it there. I'll look into it later today.

**Comment by morozov** [comment]
> 🤔 I think `tests` would have been better actually… `ci` is for files that will only ever be useful in the CI, isn't it @morozov ? Maybe there should be a new directory called `static-analysis` or `sa`?

`static-analysis` sounds good.

**Comment by derrabus** [comment]
> `static-analysis` sounds good.

`static-analysis` it is then.

**Review by greg0ire — DISMISSED** [review]

**Review by SenseException — DISMISSED** [review]

**Comment by morozov** [comment]
@derrabus, please redo. It looks like the merge commit doesn't include the current head of `3.1.x`.

**Comment by derrabus** [comment]
Done.

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks!

**Pull request merged**
