### PR TITLE
Add GitHub Actions builds for oci8 and pdo_oci drivers

### LINKED ISSUE #4075: Code coverage is not collected on Oracle builds
### Problem

1. ContinuousPHP does not integrate with CodeCov or Coveralls. Given the quality of their technical support and out of date documentation, I'm not even going to file an issue. Especially because the trust between the services needs to be on both ends.
2. We don't run tests for `pdo_oci` at all since after fixing the extension installation in https://github.com/doctrine/dbal/pull/3720, it's broken again. The documentation is outdated and still suggests to [use PHPBrew to install extensions](https://doc.continuousphp.com/php/phpbrew/).

### Migration challenges

There's no purely legal way to install an Oracle database in a public CI environment (see https://github.com/wnameless/docker-oracle-xe-11g/issues/118, https://github.com/oracle/docker-images/issues/1156) but there's a lot of bootleg distributions available including GitHub.

UPD: https://hub.docker.com/r/wnameless/oracle-xe-11g-r2/ looks alive and kicking so far.

For example, the IBM DB2 client library that our builds depend on is also publicly unavailable but we've been successfully using a copy distributed by a third-party since 2018.

### Additional resources
- https://gist.github.com/andrerom/015f43a6642cca95d03ebbf5736e2cbf
- https://github.com/strongloop/loopback-oracle-builder/tree/master/deps/oracle/Linux/x64
- https://github.com/cbandy/travis-oracle
- https://github.com/search?q=filename%3A.travis.yml+instantclient
- https://github.com/twang281314/think-model-oracle/blob/eb15e1b0ed56dc986d6d058111744c39f1fcfe51/.travis.yml
- https://github.com/pwnlabs/oracle-instantclient

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

Fixes #4075.

### CODE REVIEW

**Comment by morozov** [comment]
Not sure why code coverage didn't increase but it's not the immediate goal. Once the PR is approved, I'll remove the project from ContinuousPHP.

**Comment by greg0ire** [comment]
> Not sure why code coverage didn't increase but it's not the immediate goal

There is some insight about this in the output, apparently the file can't be downloaded.:

```
##[warning]Codecov warning: connect ETIMEDOUT 35.199.43.247:443
bash codecov.sh -n  -F 
codecov.sh: line 1: undefined: command not found
##[warning]Codecov warning: The process 'bash' failed with exit code 127
```

Consider removing coverage-related parts from this PR and reporting the bug to the action's author.

Also, a cool thing to do (possibly in a subsequent PR) would be to leverage job dependencies: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds

**Comment by morozov** [comment]
> Consider removing coverage-related parts from this PR and reporting the bug to the action's author.

Why remove it if it doesn't fail the build? Given the error message and the fact that the `oci8` build successfully uploaded its report, I'd just consider it a one-off runtime issue.

**Comment by greg0ire** [comment]
Yeah it does look transient. I see a lot of `S` in the output, they don't correspond to code that is supposed to run in these jobs do they? Because that would explain the coverage not increasing, and if it does, it would mean we no longer run OCI-related tests.

**Review by greg0ire — APPROVED** [review]
And if you don't have a doubt, just merge

**Comment by morozov** [comment]
> I see a lot of `S` in the output, they don't correspond to code that is supposed to run in these jobs do they?

This is probably because the PHP runtime doesn't have any DB extensions except for the one tested against. That's why a lot of `S`.

> […] it would mean we no longer run OCI-related tests.

It would be only possible if the OCI-based extensions weren't installed as claimed by the action but it's not possible because the first commit fixes the failure of the test that only runs if `oci8` is installed.

**Comment by greg0ire** [comment]
Ok, maybe CodeCov is lost because it does not have a report for 2.10.x AND oci…

**Comment by morozov** [comment]
> And if you don't have a doubt, just merge

I'm not 100% sure what's going on but I'd rather merge this as is and work on the coverage later. I'd like to get rid of ContinuousPHP and complete all the up-merges first.

**Comment by morozov** [comment]
There's definitely something weird going on beyond our code coverage settings. I just ran the tests locally with the configuration from the repository, and it worked:
```
$ phpunit -c ci/github/phpunit.oci8.xml --coverage-html $HOME/report
```
oci8-coverage

**Comment by greg0ire** [comment]
This url shows that 2 builds were received from GH. When I download them, they contain references to OCI8Exception, such as

```
<file name="/home/runner/work/dbal/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php">
        <class name="Doctrine\DBAL\Driver\OCI8\OCI8Exception" namespace="Doctrine\DBAL\Driver\OCI8">
          <metrics complexity="2" methods="1" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="6" coveredstatements="0" elements="7" coveredelements="0"/>
        </class>
        <line num="17" type="method" name="fromErrorInfo" visibility="public" complexity="2" crap="6.00" count="0"/>
        <line num="18" type="stmt" count="0"/>
        <line num="19" type="stmt" count="0"/>
        <line num="20" type="stmt" count="0"/>
        <line num="21" type="stmt" count="0"/>
        <line num="23" type="stmt" count="0"/>
        <line num="24" type="stmt" count="0"/>
        <metrics loc="25" ncloc="17" classes="1" methods="1" coveredmethods="0" conditionals="0" coveredconditionals="0" statements="6" coveredstatements="0" elements="7" coveredelements="0"/>
      </file>
```

So the issue would be that they are not "merged" with the other ones?

Also, this screen shows only reports from GH, nothing from Travis…

**Comment by greg0ire** [comment]
Ah wait, this graph shows a covered `OCIException`: https://codecov.io/gh/doctrine/dbal/commit/8cce1649b0deea971d8e3730685f36672bbd2145/graphs/sunburst

**Pull request merged**
