### PR TITLE
Removed nearly all `call_user_*` usages

### PR DESCRIPTION
**Pull request by kimhemsoe**

### CODE REVIEW

**Comment by deeky666** [comment]
LGTM although I am not sure about HHVM compat because we had issues with variable numbers of arguments calls...

**Comment by kimhemsoe** [comment]
I did not change any method signatures and travis hhvm jobs did not fail in a new way.

**Comment by deeky666** [comment]
Yeah the related failures were not related to method signatures but to method calls. Not sure if the tests do cover those cases.

**Comment by deeky666** [comment]
Okay merging, thanks @kimhemsoe !

**Pull request merged**
