### PR TITLE
Remove support for Doctrine Cache

### PR DESCRIPTION
**Pull request by derrabus**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes
| Fixed issues | N/A

#### Summary

This PR resolves the deprecations introduced by #4620 and #4624.

### CODE REVIEW

**Comment by morozov** [comment]
@derrabus I believe you can proceed here.

**Comment by derrabus** [comment]
The PR is ready. 🙂

**Review by SenseException — CHANGES_REQUESTED** [review]
Please also adapt caching.rst in the docs (https://github.com/doctrine/dbal/blob/4.0.x/docs/en/reference/caching.rst) where `$config->setResultCacheImpl($cache);` is used in an example.

**Comment by derrabus** [comment]
@SenseException The documentation will be fixed with #4652. Let's keep it out of this PR.

**Comment by morozov** [comment]
Let's keep documentation in sync with the code within each commit. Since the PR removes a method, it must remove it from the documentation as well.

**Comment by greg0ire** [comment]
Since that method is deprecated, the documentation can be removed before the method itself is removed, so if we merge #4652 , there will be nothing to remove (unless there are more occurrences than the one in #4652 ?). Let's avoid the necessary conflicts, and block this PR until #4652 is merged up?

**Comment by greg0ire** [comment]
Almost there: https://github.com/doctrine/dbal/pull/4669

**Review by greg0ire — DISMISSED** [review]

**Comment by morozov** [comment]
I still see that `setResultCacheImpl()` is referenced in the documentation although it's being removed in this PR.

**Review by SenseException — DISMISSED** [review]
@morozov The changes in caching.rst are already merged and up-merged into 4.0.x. Or do you refer to other occurrences of the method calls?

**Comment by morozov** [comment]
I was referring to https://github.com/doctrine/dbal/blob/c08fd1e52fa82ea8f0f853042e327972377a8da4/docs/en/reference/caching.rst#L11-L14

If this has been addressed in `4.0.x`, please feel free to merge.

**Comment by derrabus** [comment]
I've rebased my PR onto 4.0.x. The docs should be correct now. 🙂

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @derrabus!

**Pull request merged**
