### PR TITLE
Combine consecutives unsets

### PR DESCRIPTION
**Pull request by carusogabriel**
`unset` allow us to pass multiple values to check.

[PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) helped me on that.

### CODE REVIEW

**Comment by Majkl578** [comment]
I have mixed feelings about this one, it makes it worse to read... :/

**Comment by carusogabriel** [comment]
I did it to reduce lines, but if readability is more important, why not leave it as it is? :smile:

**Comment by Majkl578** [comment]
I personally think it is, but let @Ocramius decide. :)

**Comment by Ocramius** [comment]
@Majkl578 the readability is quite OK, I just think we aren't used to variadic isset/unset. I myself learned about it just 2 years ago, and I do PHP since aaaaaaages (sadly).

The change is semantically more correct, as this is an atomic operation, so a grouped unset is better than a sequence of unset calls anyway.

**Pull request merged**
