### PR TITLE
Documentation and code styling fixes

### PR DESCRIPTION
**Pull request by BenMorel**
This fixes:
- incorrect / incomplete / missing PHPdoc
- wrong case for method names
- unused imports

### CODE REVIEW

**Comment by deeky666** [comment]
@BenMorel thanks!

**Comment by BenMorel** [comment]
@lastzero This PR has been [merged into master](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php#L1108), but [not into the 2.5 branch](https://github.com/doctrine/dbal/blob/2.5/lib/Doctrine/DBAL/Connection.php#L1111), not sure why. Maybe  @deeky666 can explain how/when merges between branches happen?

**Comment by lastzero** [comment]
@BenMorel Thank you for the quick feedback! It's a bit confusing, even though PHP is not case sensitive.

**Comment by Ocramius** [comment]
> not sure why

We backport only bugfixes that may not affect behavior for current users.
This will get into 2.6

**Pull request merged**
