### PR TITLE
fix typo in docs

### PR DESCRIPTION
**Pull request by Lynnaut**
Fix typo in docs/en/reference/configuration.rst

|      Q       |   A
|------------- | -----------
| Type         | improvement
| Fixed issues | n/a

#### Summary

Fix typo where a variable has a wrong space in docs/en/reference/configuration.rst

### CODE REVIEW

**Comment by greg0ire** [comment]
Please rebase on 3.9.x, it is also affected, and is still maintained.

**Comment by Lynnaut** [comment]
Im not sure i understand you correctly since the current head of the 3.9.x branch is a direct ancestor of this commit.
But i've cherry-picked the commit to the 3.9.x branch and force-pushed the history changes.

**Comment by greg0ire** [comment]
Great, all there was to do was change the target branch then. I just did that.

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @Lynnaut !

**Pull request merged**
