### PR TITLE
Fix annotations

### PR DESCRIPTION
**Pull request by enumag**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #3717

### CODE REVIEW

**Comment by andrew-demb** [comment]
We creating similar pull requests simultaneously 😁

#3724

**Comment by enumag** [comment]
lol looks like I was 3 mins faster but you caught one additional case that I missed. :grin: 

Closing in favor of yours.

**Comment by enumag** [comment]
Hmm actually no. I think this one is better because of the target branch.

**Comment by morozov** [comment]
Thank you, @enumag.

**Comment by manu-sparheld** [comment]
When can I expect it to be released ?
TIA

**Comment by morozov** [comment]
@manu-sparheld there's no due date for the [2.10.1](https://github.com/doctrine/dbal/milestone/74) release.

**Pull request merged**
