### PR TITLE
use newer PHP syntax

### PR DESCRIPTION
**Pull request by AlessandroMinoccheri**

### CODE REVIEW

**Comment by Ocramius** [comment]
LGTM :+1:

**Comment by Majkl578** [comment]
(I was just wondering... Why did you left out Configuration classes with the same`isset` constructs?)

**Comment by AlessandroMinoccheri** [comment]
Ops, because I haven't find those because are in two lines and my parser didn't find them. 
I open a new PR with the fix ok? @Majkl578

**Comment by Majkl578** [comment]
> I open a new PR with the fix ok?

That'd be great, don't consider it a _fix_, rather an improvement. :)

**Comment by AlessandroMinoccheri** [comment]
yeah you have again right @Majkl578 :)

**Pull request merged**
