### PR TITLE
#2714 `Sequence::isAutoIncrementsFor()` is now case-insensitive

### LINKED ISSUE #2714: Sequence::isAutoIncrementsFor() not normalising PK column
The `Sequence::isAutoIncrementsFor()` method is not normalising the PK column when computing the `$tableSequenceName` for comparison. This means primary keys with uppercase characters in them are not correctly compared and incorrectly return false. This results in Schema migration SQL incorrectly attempting to drop sequences.

I'll look to submit a patch for this.

Experienced on: Postgres 9.2, Centos 7, dbal 2.5.12, PHP 5.6

### PR DESCRIPTION
**Pull request by dhensby**
Fixes #2714

### CODE REVIEW

**Comment by Ocramius** [comment]
@dhensby please re-target this patch to `2.5` - we will backport afterwards if worth doing so.

**Comment by dhensby** [comment]
@Ocramius It is targeted at 2.5 :)

**Comment by Ocramius** [comment]
@dhensby sorry, mistyped. I mean `master` :S

**Comment by dhensby** [comment]
Done - though from a selfish point of view I'd love to see this patch make the next 2.5.x release 👼

**Comment by Ocramius** [comment]
@dhensby we'll likely get it there, it's just how we do it around here though: master first, backports after evaluation ;-)

**Comment by dhensby** [comment]
awesome - thanks.

**Comment by Ocramius** [comment]
Restarted crashed build tasks

**Review by deeky666 — APPROVED** [review]

**Comment by deeky666** [comment]
@dhensby thanks!

**Comment by deeky666** [comment]
Backported to `2.5` via c8ea13ac7aa1364f569d74faf91d4533e1d54d94 and 9362698cd46139d1c5ca2750269bc90f69597e96

**Comment by dhensby** [comment]
Thanks @deeky666 @Ocramius

**Pull request merged**
