### PR TITLE
add comment to DateTimeTz if required

### PR DESCRIPTION
**Pull request by Khartir**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #1004

#### Summary

Add database comment to DateTimeTzType if required.

### CODE REVIEW

**Comment by morozov** [comment]
@Khartir thanks for the patch. Since the code being added is related to the supported platforms, the patch needs to include functional tests as well. Please see the [testing guide](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/testing.html#integration-tests) for more details.

**Comment by Khartir** [comment]
Is this what you had in mind? I tried doing it similar to the tests for `JsonType` and `GuidType` which I used as guidelines for the fixes to the Type-class and I'm a bit confused.

**Comment by morozov** [comment]
> Is this what you had in mind?

Not really. I was hoping, the test would reproduce the actual problem of storing/fetching data from the database.

After a closer look at the details of the original issue,

> This can be an acceptable fallback if you know that your application always send the value as UTC even when the database can accept any timezone as input thanks to the datetimetz type (database not supporting timezone would still have consistent data if you always send the same timezone).

It doesn't look like it's a proper solution to the problem. As far as I understand, it will allow DBAL to be part of a data loss if the platform doesn't support storing values with the timezone. Currently, it already silently drops the timezone part in DDL and the values:
https://github.com/doctrine/dbal/blob/25496429ef4bba2352b0ced7daffe1b3dec83d13/src/Platforms/AbstractPlatform.php#L3314-L3317
https://github.com/doctrine/dbal/blob/25496429ef4bba2352b0ced7daffe1b3dec83d13/src/Platforms/AbstractPlatform.php#L2979-L2982

If a user creates a `DateTimeTz` column on a platform that doesn't support it (say MySQL), stores a value with a non-default timezone and fetches it back, what will they get? This is what I was hoping the functional test would cover.

**Comment by Khartir** [comment]
OK, I understood the original issue differently:
> However it creates an issue for the SchemaTool: the field will obviously be reported as datetime when inspecting the DB, not as datetimetz (since it does not have a datetimetz). So for platforms not supporting datetimetz natively, the special comment should be used to avoid useless updates.

Basically the problem is, if you create a table with a `datetimetz`-column on a platform that doesn't support it, the database type is simply `datetime`. If you then run the SchemaTool it reports a difference between the database and the defined schema and tries to create a migration that basically has the same code in the `up` and `down` part.
The issue of maybe loosing timezone information is not solved by this PR.

**Comment by morozov** [comment]
I'll break it down into points:
> 1. [...] if you create a table with a datetimetz-column on a platform that doesn't support it, the database type is simply datetime.
> 2. If you then run the SchemaTool it reports a difference between the database and the defined schema and tries to create a migration that basically has the same code in the up and down part.

The behavior described in #​2 is only a problem if we agree that the behavior described in #​1 is valid. Which is not the case. The very fact of the DBAL simply dropping the timezone part is a bug.

> The issue of maybe loosing timezone information is not solved by this PR.

I don't think we should be solving a side effect of a known more severe problem in order to hide it.

**Comment by Khartir** [comment]
OK in that case I have no idea on how to fix this. I'll close this PR.

**Pull request closed without merging**
