### PR TITLE
Backport removal of deprecated APIs from develop

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes

This is a backport of the following pull requests originally merged into `develop`:       https://github.com/doctrine/dbal/pull/3211, https://github.com/doctrine/dbal/pull/3257, https://github.com/doctrine/dbal/pull/3518, https://github.com/doctrine/dbal/pull/3553, https://github.com/doctrine/dbal/pull/3568, https://github.com/doctrine/dbal/pull/3577, https://github.com/doctrine/dbal/pull/3579, https://github.com/doctrine/dbal/pull/3584, https://github.com/doctrine/dbal/pull/3594, https://github.com/doctrine/dbal/pull/3606.

**TODO**:
- [x] Once this is merged, most of the pull requests above should be moved from the `4.0.0` milestone to `3.0.0`. Some of them contain more than removal of the deprecated functionality and should stay in `4.0.0`.
- [x] During the merge up, the corresponding entries should be removed from `4.0.0` section of `UPGRADE.md`.

### CODE REVIEW

**Comment by greg0ire** [comment]
So `develop` was just removed?

**Review by greg0ire — DISMISSED** [review]
Since this has already been reviewed and merged

**Comment by morozov** [comment]
> So `develop` was just removed?

It was renamed to `master`.

**Comment by morozov** [comment]
A rebase was needed to address a conflict with the changes from #4083.

**Review by greg0ire — APPROVED** [review]

**Pull request merged**
