### PR TITLE
Manually merge 3.0.x into master

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

### CODE REVIEW

**Comment by morozov** [comment]
@greg0ire please do not auto-merge. There's already a merge commit that we can use.

**Comment by morozov** [comment]
In order to address the build failure, we need to deprecate the usage of the platforms like Postrgres 9.2, etc in `2.11.x` (#3855) and drop their support in `3.0.x`.

**Comment by greg0ire** [comment]
Oh right I merged #3902, shouldn't have. I should know this, I do it all the time on the Sonata repos :man_facepalming:

**Comment by greg0ire** [comment]
IIRC we can use draft PRs to shield ourselves from my stupidity :slightly_smiling_face:

**Comment by morozov** [comment]
@greg0ire IIRC the draft PRs had problems with Travis integration. In any event, this is no `WIP` and can be reviewed.

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
> @greg0ire IIRC the draft PRs had problems with Travis integration. In any event, this is no WIP and can be reviewed.

I remember issues too at the beginning. Will try on Sonata several times and let you know.

**Pull request merged**
