### PR TITLE
Check null to save real null in database

### PR DESCRIPTION
**Pull request by maxhelias**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| Fixed issues | 

#### Summary

Applies an old todo.

### CODE REVIEW

**Review by SenseException — CHANGES_REQUESTED** [review]
Please add a new test to `ArrayTest`

**Comment by maxhelias** [comment]
@SenseException done 😉

**Review by SenseException — DISMISSED** [review]

**Comment by derrabus** [comment]
This note was aded to the code to move a breaking change into the next major version. But now that 3.0 has been released already without the change, I think we have to target 4.0 for this.

**Comment by morozov** [comment]
Personally, I'm not sure if it's a valid change, especially targeted at a major release. Having to implement the same conversion of null to null in every type is error-prone and leads to inconsistency. Instead, we should document the conversion methods as expecting a non-null value and handle nulls consistently outside of the types, i.e. during binding the value or fetching results.

Another thing is that having a type that is named "array" but allows storing arbitrary values in the database is not only unsafe from the type standpoint but is also insecure (see [object injection](https://owasp.org/www-community/vulnerabilities/PHP_Object_Injection)). More practically, `GuzzleHttp\Cookie\FileCookieJar:: __destruct()` could be used to store a serialized object in the database and have PHP create a file with an arbitrary content in an arbitrary location.

I believe you understand where I'm leading with that 😉

**Comment by morozov** [comment]
Closing in favor of https://github.com/doctrine/dbal/pull/5470.

**Pull request closed without merging**
