### PR TITLE
Start SQL Server using a synchronous command to avoid intermittent login failures

### PR DESCRIPTION
**Pull request by morozov**
See https://github.com/appveyor/ci/issues/2204#issuecomment-376326756.

### CODE REVIEW

**Comment by photodude** [comment]
we should use the `services:` option in the matrix for all versions since that's now a thing

**Comment by photodude** [comment]
[reference is the documentation](https://www.appveyor.com/docs/services-databases/). I just noticed they changed it to specify a service start via the matrix. testing it now. 
https://github.com/photodude/dbal/blob/patch-2/.appveyor.yml

unfortunately, it has hung on the first test at 4%
https://ci.appveyor.com/project/photodude/dbal/build/1.0.305/job/brmknshwme5e1nlg

**Comment by photodude** [comment]
It just progressed to 5% with major errors... I'm thinking the service failed to start.
https://ci.appveyor.com/project/photodude/dbal/build/1.0.305/job/brmknshwme5e1nlg

Guess the documentation for using the matrix service start is a bad idea

**Comment by photodude** [comment]
As per the suggestions by Appveyor and the pending improvement of https://github.com/appveyor/ci/issues/2207

The change from `Start-Service` to `net start` commands is the best current solution.

**Review by Majkl578 — APPROVED** [review]

**Comment by morozov** [comment]
@Ocramius :zap: :zap: :zap:

**Comment by Majkl578** [comment]
💣

**Comment by Ocramius** [comment]
:bee:

**Pull request merged**
