### PR TITLE
Allow doctrine/common 2.7

### PR DESCRIPTION
**Pull request by Slamdunk**
To ease the process I just edited the current constraint schema, but I would rather use caret version `^2.4` if you agree.

### CODE REVIEW

**Comment by Ocramius** [comment]
@Slamdunk 👍 thanks!

**Comment by BPScott** [comment]
Yo @Ocramius, any chance of sneaking a 2.5.6 release out? This is blocking me from using some [PHP 7.1 goodness](https://github.com/doctrine/common/releases/tag/v2.7.0) in classes that have proxies.

**Comment by Ocramius** [comment]
@BPScott @Slamdunk done 👍

**Comment by BPScott** [comment]
Amazing service, thank you!

**Pull request merged**
