### PR TITLE
Adds support for setting the charset in SQLSrv

### PR DESCRIPTION
**Pull request by fran6co**
As seen here => http://technet.microsoft.com/en-us/library/cc626307(v=sql.105).aspx

### CODE REVIEW

**Comment by b-durand** [comment]
@Ocramius why it's only merged into master? BC in 2.4 when you update since v2.2. v2.5 is not supported by Symfony v2.6.6, see symfony/symfony-standard@acd2c335957a0bc2377367c0547a50f4eb05f1a2. Can you backport in branch 2.4 please?

**Comment by Ocramius** [comment]
@b-durand it's an improvement: we don't backport improvement.

Also, the world does not rotate around symfony.

**Comment by peterrehm** [comment]
@b-durand Have you tried it? With ORM 2.5 you maybe will not have issues.

**Comment by GeeH** [comment]
LIES! The world *does* revolve around Symfony and you know it.

**Comment by PeeHaa** [comment]
> Also, the world does not rotate around symfony ;-)

[citation needed]

**Comment by Ocramius** [comment]
@PeeHaa like `Ipse dixit`?

**Comment by PeeHaa** [comment]
Ah right. It's on [the web](https://github.com/doctrine/dbal/pull/699#issuecomment-91383780) so it is true.

**Pull request merged**
