### PR TITLE
Add all missing MariaDB keywords to the MySQL platform

### PR DESCRIPTION
**Pull request by roelvanduijnhoven**
Version 10.2.4 introduced `rows`  as a keyword. As doctrine does not escape non-keyword column names; this breaks stuff. And thus this prevents us from upgrading to the lastest MariaDb version.

You connect to MariaDb using the MySql connectors from Doctrine. Thus I think it would be wise to add the new keywords to this file. 

I added all missing keywords from https://mariadb.com/kb/en/mariadb/reserved-words/ and resorted the table in this PR.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
LGTM

@deeky666 can you check this? Do we have a way to test this properly?

**Comment by leofeyer** [comment]
Also see: https://jira.mariadb.org/browse/MDEV-13339

According to the MariaDV devs, `rows` will be a reserved keyword in MySQL 8.0. @Ocramius There is a `MySQLKeywords` and and `MySQL57Keywords` class. Do we need a `MySQL80Keywords` class?

**Comment by Ocramius** [comment]
@leofeyer sadly yes, although we don't have a platform for it yet

**Comment by roelvanduijnhoven** [comment]
@Ocramius Isn't it much simpler to simply escape all column names in an upcoming version? I see there is already some work done on that area: https://github.com/doctrine/dbal/issues/1592. Better investment of time than manually updating those keyword files I'd say.

**Comment by Ocramius** [comment]
We can do it in 3.*, bit quoting by default has issues with case
sensitivity handling on some engines.

**Comment by roelvanduijnhoven** [comment]
What if we simply make the quoting behaviour configurable per engine? We can then already land this in the next minor increment of this repo. For MySQL (and other engines that support this) we can remove the keywords altogether; and simply enable quoting for that engine

**Comment by Ocramius** [comment]
It really is much simpler: we'll move to quoting-only for 3.x, not in 2.x

**Comment by Ocramius** [comment]
:ship: 

Thanks @roelvanduijnhoven!

**Comment by ausi** [comment]
@Ocramius is it possible to merge this into the 2.5 branch too and release a 2.5.14 version?

Currently it is not possible to use MariaDB 10.2.4 together with PHP 5.6 or 7.0 because doctrine/dbal 2.6 requires at least PHP 7.1.

**Comment by Ocramius** [comment]
@ausi no, this is an improvement on the API. If you want to use a newer version of MariaDB, then upgrade also DBAL and consequently PHP.

**Comment by ausi** [comment]
OK, thanks for checking!

**Comment by roelvanduijnhoven** [comment]
I just migrated, and it failed. 

Turns out the `rows` keywords is _not_ escaped if used within an UPDATE statement :thinking:. Not sure why. the `MysqlKeywords` file isn't even used when generating an update query it seems.

`rows` _is_ properly escaped for alter and create statements.

Is this intended behaviour? Not sure if I should open an issue here.

**Comment by xcy7e** [comment]
Manually fixed this in 4.4 LTS and it worked. Why not change the 4.4 globally? Any reason?

**Comment by fritzmg** [comment]
@xcy7e what exactly are you referring to?

**Pull request merged**
