### PR TITLE
Fix bug about get default params on PoolingShardConnection

### PR DESCRIPTION
**Pull request by vincentchalamon**

### CODE REVIEW

**Comment by Ocramius** [comment]
@vincentchalamon please *add* a test, don't modify existing ones, unless they're wrong.

**Comment by vincentchalamon** [comment]
@Ocramius Existing tests were wrong. `getParams` method was supposed to return the `global` section of params merged with all params, instead of params only

**Comment by deeky666** [comment]
@vincentchalamon thanks!

**Comment by vincentchalamon** [comment]
@deeky666 Thanks for merging. Do you know when a new release of `doctrine/dbal` will be published ?

**Comment by deeky666** [comment]
@vincentchalamon this fix is part of 2.5.3 which is published already quite some time.

**Pull request merged**
