### PR TITLE
[DB2] Add "graphic" and "vargraphic" types

### PR DESCRIPTION
**Pull request by phansys**
|      Q       |   A
|------------- | -----------
| Type         | feature
| Fixed issues | n/a

#### Summary

See:
* https://www.ibm.com/docs/en/db2/11.1?topic=sf-graphic
* https://www.ibm.com/docs/en/db2/11.1?topic=sf-vargraphic

#### ToDo

- [x] Add unit tests;
- [x] Add functional tests.

### CODE REVIEW

**Comment by derrabus** [comment]
Tests? 🙃

**Comment by phansys** [comment]
@derrabus, I've added unit and functional tests. Could you please confirm if it is enough or if I'm missing something else? Thank you!

**Comment by derrabus** [comment]
Sorry, I'm a little busy and a bit behind with my reviews. First of all, thank your for your PR. Can you please explain what those `GRAPHIC` types are exactly? I see that you're mapping them to strings, but what's the difference to a `VARCHAR`? The documentation page that you're linking explains a function and not a type which confuses me even more.

Next thing is the functional test. I believe that it would pass without your changes. If that's the case, your test is not covering your change so we might need a different one.

Can you explain in a few sentences which problem you actually want to solve with your PR? What are you currently trying to do with those `GRAPHIC`/`VARGRAPHIC` types that does not work with DBAL? The answer to that question could help us to write a better functional test. Or it makes us realize that we don't need this change after all.

**Comment by phansys** [comment]
>Sorry, I'm a little busy and a bit behind with my reviews. First of all, thank your for your PR.

Don't worry, no problem at all. Thank you for your effort.

> Can you please explain what those GRAPHIC types are exactly? I see that you're mapping them to strings, but what's the difference to a VARCHAR?

IIUC, the main difference is that `GRAPHIC` types are specially intended to work with unicode data (encoded using UTF-16), where the length in bytes is not the same as the characters' length ([ref. from DB2 11 for z/OS](https://www.ibm.com/docs/en/db2-for-zos/11?topic=data-creating-unicode-table))

>The documentation page that you're linking explains a function and not a type which confuses me even more.

I understand your concerns. I'm neither familiarized with IBM to have a clear answer about it. I didn't found more meaningful docs related to the `GRAPHIC` and `VARGRAPHIC` types. As you can see, every data type seems to be exposed as a function there.

>Next thing is the functional test. I believe that it would pass without your changes. If that's the case, your test is not covering your change so we might need a different one.

I'm pushing a new commit where only the functional tests are kept, in order to expose the covered behavior.

>Can you explain in a few sentences which problem you actually want to solve with your PR? What are you currently trying to do with those GRAPHIC/VARGRAPHIC types that does not work with DBAL? The answer to that question could help us to write a better functional test. Or it makes us realize that we don't need this change after all.

I'm trying to allow DBAL work with these types because I think they should be supported (at least, I didn't identify a blocker for them). See the [failing pipeline](https://github.com/doctrine/dbal/actions/runs/4662900470/jobs/8253783625?pr=6001#step:10:108
) at #6001.

```shell
Doctrine\DBAL\Exception: Unknown database type graphic requested, Doctrine\DBAL\Platforms\DB2111Platform may not support it.
```

**Pull request closed without merging**
