### PR TITLE
Rename Comparator::diffTable() params - from/to instead of 1/2

### PR DESCRIPTION
**Pull request by mvorisek**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | no issue, pure refactor

#### Summary

swapping input of `Comparator::diffTable` will produce completely different result - the first gven table is expected to be the "from" table and the 2nd table is expected to be the "to" table

the names are also consistent with `Comparator::compare` (which uses `$fromSchema`, `$toSchema` names)

no more changes in `Comparator` class needed - `Comparator::diffSequence` uses `$sequence1` and `$sequence2` names, but the inputs can be swapped, so these names should stay

### CODE REVIEW

**Comment by greg0ire** [comment]
Please kindly squash your commits together. If you don't, we'll try to remember to do it for you but it's best if you save us this trouble.

**Comment by mvorisek** [comment]
@greg0ire squashed

**Review by greg0ire — DISMISSED** [review]
Let's do this before it becomes a BC-break 👍

**Review by morozov — DISMISSED** [review]

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Rebasing because of new pipeline

**Comment by greg0ire** [comment]
Thanks @mvorisek !

@morozov Codecov is behaving a bit weird, it seems to need time to process the ~50 reports we send, then it show the right percentage diff in Github's UI, but in its own UI, it's correct in some places, outdated and alarming in some others, for example the Coverage change tab is wrong and so is the Overview graph cc @thomasrockhu

**Comment by thomasrockhu** [comment]
@greg0ire, this is indeed strange. Would you be able to open a ticket in our community boards? I'll take a look.

**Comment by greg0ire** [comment]
Looks like it's fixed now, it just seems to take a lot of time. Should I still open the ticket? It will be hard for you to investigate anything I'm afraid.

**Comment by thomasrockhu** [comment]
@greg0ire, ah got it. I'll keep an eye out, but if you see it happening, please feel free to open.

**Pull request merged**
