### PR TITLE
postgresql 10 error

### PR DESCRIPTION
**Pull request by josephzhao**
SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist  
  LINE 1: SELECT min_value, increment_by FROM "logos_id_seq"

### CODE REVIEW

**Comment by Ocramius** [comment]
This requires a test case

**Comment by Majkl578** [comment]
Definitely looks like duplicate of #2868 / #2893. Should be working in master.

**Comment by iquad** [comment]
@Majkl578 how can I use master branch or dbal 2.7 with ORM? Using symfony 3.3 and it is currently using ORM 2.5.

**Comment by Ocramius** [comment]
@iquad you'd just upgrade the dependencies in `composer.json`

**Comment by Majkl578** [comment]
Closing here, duplicate of #2893, fixed in DBAL 2.7.

**Pull request closed without merging**
