### PR TITLE
Problem with drop database on PostgreSQL

### PR DESCRIPTION
**Pull request by Cinal**
Hello,

After upgrading doctrine/dbal from version v2.4.3 to v2.4.4 I couldn't drop database with zero open connections.

Example:

./app/console doctrine:database:drop --force
Could not drop database for connection named "test"
An exception occurred while executing 'DROP DATABASE "test"':

SQLSTATE[55006]: Object in use: 7 ERROR:  cannot drop the currently open database

details:
• PostgreSQL 9.2.4
• PHP 5.5.10

Any suggestions or workarounds for this issue.

Thank you

### CODE REVIEW

**Comment by Ocramius** [comment]
@Cinal if this is a bug report, please use our issue tracker: http://www.doctrine-project.org/jira/browse/DBAL

You probably want to read our release notes at http://www.doctrine-project.org/2015/01/12/dbal-244-251.html

**Comment by fprochazka** [comment]
I don't see your commits. You should probably rebase your fork properly and push again.

On the second look, this looks like an attempt for issue. For issues [there is jira](http://www.doctrine-project.org/jira), this is not how you open an issue for doctrine projects ;)

**Comment by Cinal** [comment]
sorry for this MR i wanted create issue... thx for info

**Comment by deeky666** [comment]
For reference, this is an issue that should be fixed in DoctrineBundle. PR provided: https://github.com/doctrine/DoctrineBundle/pull/368

**Pull request closed without merging**
