### PR TITLE
Manually merge 3.0.x into master

### PR DESCRIPTION
**Pull request by morozov**

### CODE REVIEW

**Comment by morozov** [comment]
The build is failing due to https://psalm.dev/r/996013af45 which affects the build because the GitHub action doesn't specify a tag:
https://github.com/doctrine/dbal/blob/78850f4ae4b6b868d685fc3c82989ef27726144b/.github/workflows/static-analysis.yml#L62
Which maps to an unstable release:
```
Psalm dev-master@234eae6ad00b38340800a779328b1d4e2d5b6bde
```

**Comment by morozov** [comment]
Let's wait until https://github.com/doctrine/dbal/pull/4353 is resolved and merged up. This will also pull in the changes from https://github.com/doctrine/dbal/pull/4348.

**Comment by morozov** [comment]
@greg0ire some jobs didn't start even after I reopened the PR. Not sure where "PHPUnit with IBM DB2 (8.0)" comes from. It's no in the build matrics and isn't expected to work yet.

**Review by SenseException — APPROVED** [review]
All builds are green now.

**Comment by greg0ire** [comment]
> Not sure where "PHPUnit with IBM DB2 (8.0)" comes from.

@morozov I believe it comes from a try @derrabus did. 

The setting will show you anything that happened, even it wasn't merged. That's why you may see `pdo_mysql` and `pdo-mysql` in the list, for instance.

**Comment by morozov** [comment]
Hm… how do we get them off the list? In my experience, removing Travis is quite non-straightforward. On a personal project, I ended up removing all the webhooks, etc. manually.

If somebody just files a PR with the matrix changes, and they persist in our branch settings just because of that, it's quite disturbing.

**Comment by greg0ire** [comment]
> Hm… how do we get them off the list?

By waiting for one week I think :sweat_smile:  

> Status checks found in the last week for this repository

**Pull request merged**
