### PR TITLE
Remove inconsistencies in table/column escaping for mysql

### PR DESCRIPTION
**Pull request by belgattitude**
Might prevent possible future bugs with reserved keywords.

### CODE REVIEW

**Comment by Ocramius** [comment]
> future bugs with reserved keywords.

Anything we can do to assess that? A regression prevention test?

**Comment by belgattitude** [comment]
Was hypothetical ;) 

Anyway quoting table and columns with '`' (which was 50% done) would give some guarantee. But not very important anyway... Feel free to close the P/R, I don't feel urgency to work on this (just added while discovering the code to fix https://github.com/doctrine/dbal/pull/2825)

**Comment by Ocramius** [comment]
@belgattitude the reasoning is quite simple: I need a test that justifies a change in the code. I'd rather have this fail with new MySQL versions (with existing tests) than a change now with no evidence of failure.

**Comment by belgattitude** [comment]
@ocramius thanks I understand. I'll close this one. 

 Keep the good work :)

**Pull request closed without merging**
