### PR TITLE
Improve ConnectionTest by triggering real exceptions

### PR DESCRIPTION
**Pull request by grongor**
The `Connection` functional test now checks real exceptions triggered by the database and not manually thrown one in the test. Relates to https://github.com/doctrine/dbal/pull/3424#pullrequestreview-189427372 but may be merged regardless/independently, imo.

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | none, but relates to #3423

### CODE REVIEW

**Comment by simPod** [comment]
@morozov I rebased this and seems like it's ready for review

**Comment by morozov** [comment]
@simPod looks good. Please squash (we don't need a commit that fails the build) and rebase on `3.2.x` (since it's not a bugfix).

**Comment by simPod** [comment]
@morozov done, can you or @grongor change base to 3.2.x? Don't have permissions since it's not really my PR 🙃

**Comment by morozov** [comment]
Done. You'll need to force-push again since there doesn't seem to be any build that I could restart.

**Comment by simPod** [comment]
It's ready for review now.

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks, @grongor, @simPod!

**Pull request merged**
