### PR TITLE
PHP 7.1 typing

### PR DESCRIPTION
**Pull request by tolbon**
Hello, I am working on "typing DBAL" because now minimum version is 7.1 and PHP add this new feature.

WORK IN PROGRESS

this work permit to see some inaccurate docs

### CODE REVIEW

**Comment by jvasseur** [comment]
Adding a type hint to anything that can be extended is a BC break with PHP < 7.2

**Comment by tolbon** [comment]
I am sorry I don't understand why it is BC break ?
composer.json say minimum supported version is PHP 7.1 so I use feature of PHP 7.1

maybe I do it wrong ?

**Comment by jvasseur** [comment]
If have create a class extending one of doctrine's class in your project, adding types in doctrine means your code will break with "incompatible method signature" errors.

The only place we can add types is in method constructors (since they don't have to be compatible) and final classes/methods (since they can't be extended).

With PHP 7.2 we could do it on method arguments (but not method return types): https://wiki.php.net/rfc/parameter-no-type-variance

**Comment by tolbon** [comment]
Oh I understand now. So I close this PR ?

**Comment by jvasseur** [comment]
You can keep the changes for constructors and methods of final classes.

**Pull request closed without merging**
