### PR TITLE
Manually merge 2.10.x into 2.11.x

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by morozov** [comment]
@greg0ire is it still a draft? You may have requested a review for the wrong PR.

**Comment by greg0ire** [comment]
@morozov I'm using the draft status to avoid an accidental merge, please review it anyway.

**Comment by greg0ire** [comment]
But please make sure you start here: https://github.com/doctrine/dbal/pull/3960 😅

**Comment by greg0ire** [comment]
Okay it's finally ready @morozov , please review.

**Review by morozov — APPROVED** [review]

**Pull request merged**
