### PR TITLE
Invalid sp_rename with case sensitive DB (sp_RENAME -> sp_rename)

### PR DESCRIPTION
**Pull request by redgnar**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

#### Summary

In MSSQLs DBs that use case sensitive collation, the command sp_RENAME will not work. It should be sp_rename, it is proper command name

### CODE REVIEW

**Comment by greg0ire** [comment]
Please associate your email address with your Github account, or change the
email in your commits to an address already associated with it. If you do not
want to expose your personal email address, you may use
`$userName@users.noreply.github.com`, that way we can still reach you through Github.
Additionally, you will get credit for this contribution on your Github profile.

**Comment by greg0ire** [comment]
> It should be sp_rename, it is proper command name


Source: https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-rename-transact-sql?view=sql-server-ver15

**Review by greg0ire — DISMISSED** [review]

**Comment by redgnar** [comment]
Ok 👍

**Review by morozov — CHANGES_REQUESTED** [review]
This change requires steps to reproduce and an integration test that fails without the fix. This way, we'll make sure that DBAL is tested with this previously untested configuration and likely find other similar issues.

If a test is impossible to implement in the current environment, consider adding another AppVeyor or Travis build.

**Comment by redgnar** [comment]
> This change requires steps to reproduce and an integration test that fails without the fix. This way, we'll make sure that DBAL is tested with this previously untested configuration and likely find other similar issues.
> 
> If a test is impossible to implement in the current environment, consider adding another AppVeyor or Travis build.

Such test requires mssql instance with CS collation for example Polish_CS_AS. If you have such db you can change something like column:

`create table example
(
	id nvarchar(50) not null
		primary key,
	testcol nvarchar(50)
)
go`

`exec sp_RENAME 'example.testcol', testcol_new, 'COLUMN'
go`

You will receive error that there is no procedure sp_RENAME.

Really I don't know how to reproduce it in AppVeyor or Travis. I don't know how you handle it in dbal (calling test on real db automatically). Do you have some manual or can you help me with that ?

**Comment by redgnar** [comment]
I think you can reproduce this error by changing collation of doctrine_tests db to Latin1_General_100_CS_AS

**Comment by redgnar** [comment]
> This change requires steps to reproduce and an integration test that fails without the fix. This way, we'll make sure that DBAL is tested with this previously untested configuration and likely find other similar issues.
> 
> If a test is impossible to implement in the current environment, consider adding another AppVeyor or Travis build.

I think you can reproduce this error by changing collation of doctrine_tests db to Latin1_General_100_CS_AS

**Comment by greg0ire** [comment]
How does one do that? Should it be done here: https://github.com/doctrine/dbal/blob/2.10.x/tests/travis/install-mssql.sh

Or should the config block that uses that file be duplicated and an `configure-mssql-cs.sh` be created, so that we have one job with a CS db, another with a CI db?

**Comment by redgnar** [comment]
There is docker env MSSQL_COLLATION. You can set it to "Latin1_General_100_CS_AS". It should be enought to reproduce error.

**Comment by greg0ire** [comment]
Ok so maybe you can duplicate this block:
https://github.com/doctrine/dbal/blob/1efdc639b66392c396937775b4f426e129688462/.travis.yml#L214-L221

And set that variable in the environment, and in the script, pass it to docker if it is defined?

**Comment by redgnar** [comment]
And add it to this PR or create new one ?

**Comment by redgnar** [comment]
I can see there are other problems with CS as well

**Comment by redgnar** [comment]
I fixed other issues with CS. SysObjects and SysColumns. Should be sysobjects and syscolumns

**Comment by greg0ire** [comment]
The code looks good, but you have 3 commits that are all labelled the same way. I think there should be maybe 2 commits, one with the renames (plural), and the second that would setup the new build job.

**Pull request closed without merging**
