### PR TITLE
Merge 3.3.x up into 3.4.x

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by morozov** [comment]
Shouldn't we merge changes up manually to avoid double merge commits?

**Review by morozov — APPROVED** [review]

**Comment by greg0ire** [comment]
That's only in case of conflict. Here, there was none (my fork is not in use).

**Comment by greg0ire** [comment]
Weird, that did not make the commits disappear from https://github.com/doctrine/dbal/pull/5217 :thinking:

**Comment by morozov** [comment]
> That's only in case of conflict.

I didn't know that but it looks like you're right (e.g. judging by the https://github.com/doctrine/dbal/pull/5203 outcome).



> Weird, that did not make the commits disappear from #5217 🤔

It never worked this way in my experience. IIRC, I googled about it recently, and it was a known behavior/limitation of GitHub.

**Pull request merged**
