### PR TITLE
Run tests on PHP 8.2

### PR DESCRIPTION
**Pull request by derrabus**
PHP 8.2.0-alpha1 has been released and I think we should start monitoring our compatibility with the next PHP version.

### CODE REVIEW

**Comment by derrabus** [comment]
The tests fail with OCI8 on this line:

> Creation of dynamic property OCILob::$descriptor is deprecated

https://github.com/doctrine/dbal/blob/e15d05d08172ceeb4f55066feed48d688fdb0250/src/Driver/OCI8/Statement.php#L75

Looks like a PHP bug to me.

**Comment by derrabus** [comment]
Reported as php/php-src#8756

**Comment by derrabus** [comment]
The OCI8 issue has been fixed upstream. CI is green now.

**Comment by morozov** [comment]
> The OCI8 issue has been fixed upstream. CI is green now.

Thanks for taking care of it, @derrabus!

**Review by morozov — APPROVED** [review]

**Pull request merged**
