### PR TITLE
Drop support for SQL Server 2016 and older

### PR DESCRIPTION
**Pull request by morozov**
The mainstream support has ended ([source](https://docs.microsoft.com/en-us/lifecycle/products/sql-server-2016)).

### CODE REVIEW

**Comment by derrabus** [comment]
Shall we rename `SQLServer2012Platform` to `SQLServer2017Platform` then?

**Comment by derrabus** [comment]
… or deprecate&drop `SQLServer2012Platform` completely? The name of the class is highly confusing, we only support 2017 and onwards.

**Comment by morozov** [comment]
`SQLServer2012Platform` _was_ removed in https://github.com/doctrine/dbal/pull/4763. Now, `SQLServerPlatform` is explicitly documented as:

https://github.com/doctrine/dbal/blob/86322856e6802526c9f023820452bcc96a0eced7/src/Platforms/SQLServerPlatform.php#L46-L49

We decided not to have a version in the class name representing the oldest supported version. It will help avoid extra diffs when dropping old platforms, also https://github.com/doctrine/dbal/pull/4755#discussion_r696142079.

**Comment by derrabus** [comment]
Oh, I didn't see that. 🙈

**Review by derrabus — APPROVED** [review]

**Pull request merged**
