### PR TITLE
Drop Drizzle support

### PR DESCRIPTION
**Pull request by BenMorel**
As suggested in #3039

### CODE REVIEW

**Comment by kimhemsoe** [comment]
https://github.com/doctrine/dbal/pull/767

**Review by Majkl578 — APPROVED** [review]

**Comment by Majkl578** [comment]
@kimhemsoe If you are okay with that, lets keep this PR, the one referenced is old and full of conflicts. :|

**Comment by Majkl578** [comment]
@BenMorel Please also add note to UPGRADE.md.

**Comment by BenMorel** [comment]
@kimhemsoe Sorry for the dup, I should've searched better!
@Majkl578 Done!

**Comment by kimhemsoe** [comment]
@Majkl578 Yeah ofc no problem. Only linked it so we remembered to close it.

**Pull request merged**
