### PR TITLE
Support symfony 6

### PR DESCRIPTION
**Pull request by arvodia**
Fixed

|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

#### Summary

Support symfony 6

### CODE REVIEW

**Comment by derrabus** [comment]
This is a breaking change that we cannot apply to the 3.1.x branch. Apart from that, the command is compatible with Symfony 6 without adding this return type. Thanks for proposing, though.

**Comment by arvodia** [comment]
in symfony 5.4+ you have to add the value of return otherwise you will see the depreciation message in the log 
otherwise I will add in annotation the value of return ?

**Comment by derrabus** [comment]
This has happened already, see #4970.

**Comment by arvodia** [comment]
ok i m sorry 
but why the commit is not applied?
you haven't yet emerged

**Comment by derrabus** [comment]
We haven't tagged releases with that change yet. We will do so in time. This isn't really urgent, is it?

**Comment by arvodia** [comment]
thank you for your reply
I will delete this post
I have already made a patch to have an empty log

**Pull request closed without merging**
