### PR TITLE
SchemaDiff fails to detect missing default value on nullable column

### PR DESCRIPTION
**Pull request by janedbal**
|      Q       |   A
|------------- | -----------
| Type         | bug
| Fixed issues | 0

#### Summary

As seen in the failing test, database column missing proper default value is not detected by schema diffing.

### CODE REVIEW

**Comment by derrabus** [comment]
The issue that we're seeing here is that DBAL cannot distinguish a nullable column with a default value of `NULL` and a nullable column without a default, did I get this right?

**Comment by janedbal** [comment]
@derrabus ~Not just that, any default value difference is not detected. So even if you setup default value e.g. `666` and than run `ALTER COLUMN col1 DROP DEFAULT`, dbal is unable to detect that live db is mismatching that original schema.~

**Comment by janedbal** [comment]
Sorry, that is not correct, only that nullability without default value is not detected.

**Comment by derrabus** [comment]
Okay, so that's a limitation of our data model. Our `Column` class has the properties `$_default` and `$_notnull` which are interpreted like this:

| `$_notnull` | `$_default` | Actual default |
| --- | --- | --- |
| `true` | any string literal | the specified literal |
| `true` | `null` | No default |
| `false` | any string literal | the specified literal |
| `false` | `null` | `null` |

As you can see, your edge case of a nullable column without a default cannot be modeled here. This is why DBAL also cannot introspect the table properly.

tbh, I'm not sure if implementing this feature actually makes sense. We'd probably have portability issues because not all engines allow to have a nullable column without a default.

**Comment by derrabus** [comment]
I've opened an issue, in case somebody wants to work on this topic: #6084

**Pull request closed without merging**
