### PR TITLE
ExpressionBuilder: Support array arguments for orX, andX

### PR DESCRIPTION
**Pull request by jnvsor**

### CODE REVIEW

**Comment by jnvsor** [comment]
Would a ternary if be preferred? It does go over 100 char line length if I do that though.

**Comment by morozov** [comment]
Starting PHP 5.6 you can use the `andX(...$array)` syntax with the existing implementation.

**Comment by jnvsor** [comment]
I'm aware of that but DBAL supports down to 5.3 (Should I have made this PR against a different branch?)

**Comment by morozov** [comment]
As far as I can tell, only DBAL v2.5 supports PHP 5.3, and this PR proposes a new feature which should go to the new minor release (like v2.6), but it will not support PHP 5.3.

**Comment by jnvsor** [comment]
Ah, I wasn't aware 2.6 would drop 5.3 support - thought that was for the next major version. Never mind!

**Pull request closed without merging**
