### PR TITLE
Add support using on alter column (pgsql)

### PR DESCRIPTION
**Pull request by pvsaintpe**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | #3615

### CODE REVIEW

**Review by SenseException — CHANGES_REQUESTED** [review]
Thank you for your contribution. Before you start to fix what breaks the tests, can you please squash the phpcs commits into one commit and give it a more descriptive message?

**Comment by pvsaintpe** [comment]
> Thank you for your contribution. Before you start to fix what breaks the tests, can you please squash the phpcs commits into one commit and give it a more descriptive message?

Ok!

**Comment by SenseException** [comment]
Do you ask for help for the squash of the phpcs commits? If you're unfamiliar with squashing commits, I can offer my help.

**Comment by pvsaintpe** [comment]
> Do you ask for help for the squash of the phpcs commits? If you're unfamiliar with squashing commits, I can offer my help.

Thank you, Because I don’t understand how I can squash the phpcs commits

**Comment by greg0ire** [comment]
1. `git rebase -i origin/master`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin/whatever-you-call-it repository.
2. A window will show up with many lines, replace `pick` with `fixup` on every line but the first one
3. Close your editor, git should do its magic, and you should end up with one commit
4. Use `git push --force` to overwrite what you already push. Don't forget the `--force` option otherwise git will try to merge both things together.

**Pull request closed without merging**
