### PR TITLE
Introduce Statement::fetchFirstColumn()

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

See the discussion starting https://github.com/doctrine/dbal/pull/4019#issuecomment-635174952.

### CODE REVIEW

**Review by greg0ire — COMMENTED** [review]
I think there should be changes in `docs/en/reference/data-retrieval-and-manipulation.rst`

**Comment by morozov** [comment]
@greg0ire do you have anything specific in mind? If you're talking about `fetchAll(FetchMode::COLUMN)`, it wasn't documented there.

**Review by greg0ire — APPROVED** [review]
Ah I didn't check… since you changed things in that piece of documentation last time, I thought every method was documented.

**Comment by derrabus** [comment]
Thank you very much! ❤️

**Pull request merged**
