### PR TITLE
Move website config to default branch

### PR DESCRIPTION
**Pull request by SenseException**
Adapts the website config to be compatible with the doctrine/doctrine-website#356 changes

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | /no

### CODE REVIEW

**Review by greg0ire — DISMISSED** [review]

**Comment by SenseException** [comment]
I need to change the target branch for this PR. See https://github.com/doctrine/dbal/pull/4309#issuecomment-700065534

**Comment by greg0ire** [comment]
Yes sorry, I'm on my phone, see #4309 for details

**Comment by SenseException** [comment]
@greg0ire Now it should fit as soon as `2.11.x` is new default branch.

**Review by greg0ire — APPROVED** [review]
LGTM, even if 3.0.x ends up staying the default branch, since we frequently merge things up.

**Comment by greg0ire** [comment]
Thanks @SenseException !

**Pull request merged**
