### PR TITLE
[WIP] [3.0] Extract getSequenceNumber() from lastInsertId()

### PR DESCRIPTION
**Pull request by BenMorel**
***Work In Progress**: this requires #3335 and #3367 to be merged first. Their commits are included here; this PR actually starts at commit 69b6f3d.*

*I'm opening this PR early to be able to run CI tests on all platforms, and will rebase it later.*

|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes
| Fixed issues | N/A

#### Summary

While talking about `Driver\Connection::lastInsertId()`, @morozov [suggested the idea](https://github.com/doctrine/dbal/pull/3335#pullrequestreview-178029897) that:

> (...) the calls with and without the $name are targeted at the same method but have totally different semantics (named sequences and identity columns). This confusing API was originally borrowed from PDO but we don't have to follow it strictly.

#### Proposed changes

This PR splits the existing `lastInsertId(?string $name = null) : string` method into 2 methods:

- `lastInsertId() : string`
- `getSequenceNumber(string $name) : string`

Naming is a first draft, suggestions welcome (`getLastInsertId()` for consistency?)

[Tests have been extended](https://github.com/doctrine/dbal/blob/94d0416669aff460bd7c6ae54a83d4ddfae49d38/tests/Doctrine/Tests/DBAL/Functional/WriteTest.php#L149-L211) to cover the following scenarios:

- `lastInsertId()` on supported platforms
- `lastInsertId()` on unsupported platforms (exception)
- `lastInsertId()` on all platforms, on a fresh connection, i.e. with no ID available (exception)
- `getSequenceNumber()` with a known sequence name on supported platforms
- `getSequenceNumber()` with an unknown sequence name on all platforms (exception)

### CODE REVIEW

**Comment by BenMorel** [comment]
@morozov Same here, has this been implemented elsewhere?

**Comment by morozov** [comment]
No. GitHub closed this automatically.

**Comment by morozov** [comment]
@BenMorel are you planning to work on this? This is definitely what I'd like to see in 3.0.

**Comment by BenMorel** [comment]
@morozov I'm trying to rebase the relevant commits onto master. There's quite some work do to, but I should get there. We'll see how it goes.

**Comment by BenMorel** [comment]
@morozov Please see this new PR: #3759.
There are a few tests failing with some of the drivers, I'll try to fix them tomorrow.

**Pull request closed without merging**
