### PR TITLE
[WIP] Add pdo informix driver support

### PR DESCRIPTION
**Pull request by josemalonsom**
I have created this branch to add support to PDO_INFORMIX in DBAL.

First I had put a new topic in the doctrine-dev group (https://groups.google.com/forum/#!topic/doctrine-dev/gndS00nxSQA) where i explain some issues i have.

### CODE REVIEW

**Comment by deeky666** [comment]
@zeroedin-bill @Ocramius what shall we do with this one? I tend to not have new platforms for `2.x` anymore and wait until `3.0` with that...

**Comment by mablae** [comment]
@deeky666 This is obsolete, use https://github.com/josemalonsom/ifx4dd 

I use it, and it works fine with DBAL, but I dont know about ORM.

**Comment by deeky666** [comment]
@josemalonsom @mablae neat that it is being worked on. Closing this for now then, we will reevaluate adding it to the core for `3.0`.

**Comment by josemalonsom** [comment]
Ok guys, thanks.

**Pull request closed without merging**
