### PR TITLE
Remove redundant method override

### PR DESCRIPTION
**Pull request by duncan3dc**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

#### Summary

While investigating an issue I noticed this method overrides one that is identical, so this PR just removes the duplicate.
https://github.com/doctrine/dbal/blob/da4742c31936a72a261409d75f331e6727622d6a/lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php#L1239-L1242

### CODE REVIEW

**Review by derrabus — COMMENTED** [review]
The change looks correct: the parent method does exactly the same. Not sure if it's worth merging this kind of change to 2.13.x though. On 3.3.x, this issue is fixed already.

**Comment by greg0ire** [comment]
It does not fall under any of the categories described in https://www.doctrine-project.org/2022/01/22/sunsetting-dbal-2.html, so let's close, sorry.

**Comment by duncan3dc** [comment]
It was cleanup in preparation for a bug fix (#5237) would you rather that bugfix was more complicated and updated two duplicate methods than merge this PR?

**Comment by derrabus** [comment]
We try to change as little as possible on the 2.13 branch. If a change does not fix a critical bug, we usually don't merge it anymore, especially if the problem was solved on a higher branch already.

**Comment by duncan3dc** [comment]
I don't understand the relevance of that sorry, are you saying you're rejecting the unicode/nvarchar bug fix for 2.13?

**Comment by derrabus** [comment]
No, I'm saying we're rejecting the change suggested in this PR.

**Comment by duncan3dc** [comment]
@greg0ire already said that, so then I asked if you'd rather the bugfix this is for (#5237) was more complicated, I'll presume that's a yes...

**Pull request closed without merging**
