### PR TITLE
DateIntervalType (negative support) resolves doctrine/dbal#2578

### PR DESCRIPTION
**Pull request by EHER**
- PR #2579 from @galeaspablo using suggestion from comments to support old DateInterval format.

### CODE REVIEW

**Comment by galeaspablo** [comment]
Is there any need to support the old format? BC doesn't matter inside dev branch.

**Comment by lcobucci** [comment]
> BC doesn't matter inside dev branch.

It does matter, `2.6` is a minor release not a major one.

**Comment by galeaspablo** [comment]
The old format was introduced inside 2.6 dev. If it was in 2.5, it would be a new type.

**Comment by galeaspablo** [comment]
Please also refer to https://github.com/doctrine/dbal/issues/2578#issuecomment-312047665 This is not a backwards compatibility break.

Also, please note that since https://github.com/doctrine/dbal/pull/2316 was merged, the PR needs to be changed. Which I've now donw in https://github.com/doctrine/dbal/pull/2579#issuecomment-312485175

**Comment by lcobucci** [comment]
> Please also refer to #2578 (comment) This is not a backwards compatibility break.
>
> Also, please note that since #2316 was merged, the PR needs to be changed. Which I've now donw in #2579 (comment)

You're correct, closing this one.

**Pull request closed without merging**
