### PR TITLE
Drop db support for PostgreSQL 9.3 and MariaDB 10.0

### PR DESCRIPTION
**Pull request by SenseException**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes
| Fixed issues | -
| Related | #3055

#### Summary

PostgreSQL 9.3 is an [unsupported version](https://www.postgresql.org/support/versioning/) since last year. MariaDB 10.0 support [ends in March 2019](https://mariadb.org/about/maintenance-policy/) and considering that the next DBAL major release is still far in the future compared to MariaDB 10.0, I already removed it in this PR.

### CODE REVIEW

**Comment by morozov** [comment]
Should we then merge `PostgresqlPlatform` and `PostgreSQL94Platform`?

**Comment by SenseException** [comment]
Sounds reasonable. I'll see that we keep `PostgresqlPlatform` after the "merge".

**Review by Majkl578 — CHANGES_REQUESTED** [review]
This will need a note in UPGRADE.md - you can expand the one already there from #3055.
Also please adjust information in the table in docs/en/reference/types.rst

At the end squashing into one commit would be :ok_hand:.

**Comment by morozov** [comment]
@SenseException are you planning to finish this or someone could take over?

**Comment by SenseException** [comment]
I forgot about this PR. The rebase will take a while, but I want to finish it.

**Review by morozov — APPROVED** [review]
@SenseException, looks good. Please squash.

**Comment by SenseException** [comment]
My commits are now squashed.

**Comment by morozov** [comment]
@SenseException can you confirm all commits are relevant to your ticket? As I can see, the first two are almost opposite to each other, ccf4a9da37c368c68eae1c9de8e05abee9c65dd8 is about `SQLLogger`, etc.

Please make sure only your changes are presented in the PR. I believe it should be a single commit since you were the only developer of this PR.

**Pull request merged**
