### PR TITLE
Use cache action v2

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
@morozov I noticed that the default branch is now 3.0.x, is that intended? Or was it a consequence of using automatic-releases?

**Comment by morozov** [comment]
It's not intended. It must have been changed by the release workflow. I reverted manually after the previous release but didn't yet notice the need this time.

**Review by morozov — APPROVED** [review]

**Comment by greg0ire** [comment]
> haven't yet noticed the need this time.

Are you suggesting we shouldn't change it back this time? According to https://github.com/doctrine/dbal/pull/4309 it should be if you feel otherwise please elaborate.

**Comment by morozov** [comment]
We should.

**Comment by greg0ire** [comment]
Okay, done.

**Review by SenseException — APPROVED** [review]

**Pull request merged**
