### PR TITLE
[WIP] Remove PHP 5.3 support

### PR DESCRIPTION
**Pull request by Ocramius**
Just a suggestion for master (2.6). We should move on.

### CODE REVIEW

**Comment by deeky666** [comment]
:+1: will take some time anyways until 2.6 will be released so I'm fine with it.

**Comment by stof** [comment]
Dropping it just for the matter of dropping it is not worth it IMO. This is useless if it does not allow to clean the codebase

**Comment by Ocramius** [comment]
@stof this has actually a lot of avantages for us, even though we won't change the codebase in one shot (mainly to avoid merge conflicts).

@deeky666 is setting up a complex CI environment for internal use by the doctrine org, and 5.3.x is very problematic to deal with.

Yes, that was an excuse to drop it, but there's also no good excuse to keep supporting 5.3.x.

Considering the current PHP 5.4 lifetime, we will also be able to introduce generator usage by the end of the year by dropping 5.4 support in DBAL 2.7 or such.

**Comment by Tobion** [comment]
This can be closed as #880 has been merged.

**Comment by deeky666** [comment]
Implemented in #2419

**Pull request closed without merging**
