### PR TITLE
removed an else condition, fixed a parameter annotation and make little improvements

### PR DESCRIPTION
**Pull request by AlessandroMinoccheri**

### CODE REVIEW

**Comment by Ocramius** [comment]
@AlessandroMinoccheri please don't merge `master`: rebase instead

**Comment by AlessandroMinoccheri** [comment]
Ok, sorry for the merge... do you prefer to close this and open another wth the rebase @Ocramius ?

**Comment by Ocramius** [comment]
You can just rebase your branch and force-push it 👍

**Comment by AlessandroMinoccheri** [comment]
Sure, no problem to do It

**Comment by AlessandroMinoccheri** [comment]
rebase done but travis fail... @Ocramius

**Comment by Ocramius** [comment]
@AlessandroMinoccheri failure is clear tho (and related to this change): https://travis-ci.org/doctrine/dbal/jobs/336473229#L576-L582

**Comment by AlessandroMinoccheri** [comment]
Fixed travis tests

**Comment by Ocramius** [comment]
@AlessandroMinoccheri thanks!

**Pull request merged**
