### PR TITLE
SqlitePlatform: support arithmetic expressions as interval parameter of getDateArithmeticIntervalExpression()

### PR DESCRIPTION
**Pull request by gigib82**
ref. doctrine/doctrine2#6237
Doctrine tests pass

### CODE REVIEW

**Comment by Ocramius** [comment]
Requires test cases

**Comment by gigib82** [comment]
I couldn't really find anything related to date functions in dbal test suite, can you please quickly explain me how this should be tested?

**Comment by photodude** [comment]
@gigib82 you just need to write unit tests that check to prove the code works correctly. Look at the [existing unit tests](https://github.com/doctrine/dbal/tree/master/tests) and the php unit documentation to see examples.

your referenced doctrine issue has a unit test included... it should be included here as well

**Comment by gigib82** [comment]
Yes, in the meanwhile I've (slowly) progressed with this PR and written/updated the tests, I will push  the updates as soon as I find the time to test it on all platforms since other platforms needed changes too. Thank you for replying!

**Comment by Ocramius** [comment]
If you push the tests, the CI takes care of trying out all possible
combinations for you.

**Comment by photodude** [comment]
except mssql as we are still working to include that testing... still worth pushing the tests up

**Comment by gigib82** [comment]
Screwed up with git big time :)

**Comment by lcobucci** [comment]
@gigib82 don't worry reflog is your friend :wink

**Comment by Ocramius** [comment]
That is indeed a first :D


@gigib82 no worries btw, I pushed the latest state that I saw from my PC at https://github.com/Ocramius/dbal/tree/feature/%232605-support-sqlite-platform-interval-parameter-in-date-aritmetics

**Pull request closed without merging**
