### PR TITLE
Added PostgreSQL 9.2 range types

### PR DESCRIPTION
**Pull request by Stardog**
Fixes doctrine/dbal#2353

See http://www.postgresql.org/docs/9.2/static/rangetypes.html

### CODE REVIEW

**Comment by deeky666** [comment]
@Stardog well, those native types are representing ranges of types, not atomic values (if I get the docs correctly), so how can those map to atomic values (literals)?

**Comment by Stardog** [comment]
Honestly, I was hoping it was a quick fix that would allow you to merge and move. I agree, it doesn't really fit the method's purpose. Can you suggest an alternative coding direction to approach the error that ranges cause?
Please close this if not the direction you want to go.
Thanks!

**Comment by deeky666** [comment]
@Stardog this seems highly PostgreSQL specific so I am not sure we will/can add this to DBAL core. What do you actually get from the driver when you query those columns? I mean the type system is also responsible for converting PHP types from and to SQL types. I wonder what the driver returns for those SQL types. That said, I wonder how a range (having two values, a lower and upper bound) can be converted to an atomic PHP type like `int` as your PR suggests...

**Comment by EspadaV8** [comment]
The ranges are returned as string values. We are currently making use of them extensively in an application (currently using Laravel's Eloquent) and we manually parse the string into an array of values

```php
// original from DB
$tstzrange = "[2016-01-01 00:00:00+00,2016-02-01 00:00:00+00)";

// after some string manipulation
$parsed = [
    'lower' => Carbon('2016-01-01 00:00:00+00'),
    'upper' => Carbon('2016-02-01 00:00:00+00'),
];
```

This isn't really enough information though for a standard library since the upper and lower values could either be open or closed which may be important information for the consumer of the data (we don't care because all of our `tstzrange`s are the same).

We then do some formatting from the parsed array back into the correctly formatted string before saving it into the column.

**Comment by morozov** [comment]
Closing as stale.

**Pull request closed without merging**
