### PR TITLE
Correcting references to `Driver\Connection` in the documentation

### PR DESCRIPTION
**Pull request by b0nd0**
At least it looks like one to me.

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
Should probably be https://github.com/doctrine/dbal/blob/v2.5.0/lib/Doctrine/DBAL/Driver.php

Also, please make a more descriptive commit/issue title 👍

**Comment by b0nd0** [comment]
Thanks for such quick response, i'll try to name pull requests better next time.
But speaking about changes, as far as i understand:
```
The drivers abstract a PHP specific database API by enforcing two interfaces:
...
The above two interfaces require exactly the same methods as PDO.
```
it should be `connection` and `statement`, isn't it? DBAL\Driver doesn't look like PHP PDO class

**Comment by Ocramius** [comment]
@b0nd0 ah, yep, my bad!

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
@b0nd0 thanks! \o/

**Pull request merged**
