### PR TITLE
Added Codecov uploader to Travis CI configuration

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no

### CODE REVIEW

**Comment by morozov** [comment]
What a bummer. Apparently, Codecov [doesn't support](https://docs.codecov.io/docs/about-the-codecov-bash-uploader#section-upload-token) non-authenticated report uploads from ContinuousPHP. At the same time, given that it's a public environment, we cannot securely store a secret there.

**Comment by SenseException** [comment]
Is this PR ready for a review or is it still WIP?

**Comment by morozov** [comment]
It's still WIP. I cannot marry it with other CIs than Travis.

**Comment by morozov** [comment]
Filed https://github.com/lemurheavy/coveralls-public/issues/1392.

**Pull request closed without merging**
