### PR TITLE
Modify Limit Query on SQLServer2012 with newline before `ORDER BY`

### PR DESCRIPTION
**Pull request by stchr**
Modify Limit Query on SQLServer2012 with newline before ORDER BY

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Is there a reason this PR has 3 commits? The first 2 commits seems unrelated. Maybe you should [`rebase`](https://git-scm.com/docs/git-rebase) this PR (depending on the choice from the admins of this repository).

**Comment by deeky666** [comment]
Yep should be rebased and squashed.

**Comment by Ocramius** [comment]
@billschaller if you can give me your 👍 or 👎 I can merge and rebase on merge

**Comment by billschaller** [comment]
@ocramius :+1:

**Comment by Ocramius** [comment]
Merged, thanks!

`master`: doctrine/dbal@17f50b86ef2b78d4331e60b2caead3829505c350
`2.5`: doctrine/dbal@b896ddd6fa1271d7f2bf8936ce8d069f240cd9ff

**Pull request closed without merging**
