### PR TITLE
ref #2597 Fix function getListTablesSQL() for SQL Server

### PR DESCRIPTION
**Pull request by cgardiennet**
Fix done for ref #2597! 
Waiting for review and merge !

### CODE REVIEW

**Comment by Ocramius** [comment]
Needs tests, both unit and functional ones

**Comment by cgardiennet** [comment]
@Ocramius : i'm a newbee on posting fix on github, what's needed exactly ?

**Comment by Ocramius** [comment]
See https://github.com/doctrine/dbal/blob/master/tests/Doctrine/Tests/DBAL/Platforms/SQLServerPlatformTest.php for an example of how existing tests for this platform were written. Also, a test that fails before this patch is applied, and describes what the original issue is, is needed.

We generally do not merge work without full coverage of an issue.

**Comment by cgardiennet** [comment]
@Ocramius : If i'm writing tests for this patch, do i need to create a full new PR ?

**Comment by Ocramius** [comment]
No, just keep pushing commits to the branch you were working on, and then
simply poke us when you want us to check it 👍

**Comment by photodude** [comment]
@cgardiennet have you had a chance to get to the unit tests for this? Seems like a good improvement just needs to get tests implemented.

**Comment by malandles** [comment]
Poking the thread as it's been a year already. I applied the change on my project and it fixed the related issues with the schemas and SQL Server. I am not currently able to put tests in place though.

**Comment by Majkl578** [comment]
@malandles Unfortunately tests are still missing and we can't consider bugfixes without them. If you can provide one, it could help resolving this bug/PR.

**Comment by cgardiennet** [comment]
I'll try to provide tests, but I didn't have time for this PR. And I also don't have an SQL Server DB available for now.

**Comment by Majkl578** [comment]
@cgardiennet Hi, we've added CI testing (Travis + AppVeyor) against multiple SQL Server versions recently in #2617 & #3050. You can now try writing a _blind_ functional test and see how it goes on CI without having SQL Server locally. :smirk:

**Comment by morozov** [comment]
Closing as stale and missing tests.

**Pull request closed without merging**
