### PR TITLE
Add PostgreSQL 9.6 to the build pipeline

### PR DESCRIPTION
**Pull request by photodude**
Small update since Travis has the ability to test PostgreSQL 9.6 now

### CODE REVIEW

**Comment by deeky666** [comment]
@photodude looks good to me. Can you please rebase?

**Comment by photodude** [comment]
@deeky666 I have removed the php 5.6 builds same as the other changes (something I wouldn't have done until the php 5.6 security support had ended on 31 Dec 2018... PHP 7 security support ends before php5.6's support http://php.net/supported-versions.php)

**Comment by photodude** [comment]
@deeky666 @Ocramius bump for merge consideration.

**Comment by Ocramius** [comment]
👍 thanks @photodude!

**Comment by photodude** [comment]
you are welcome

**Pull request merged**
