### PR TITLE
Merge 3.9.x up into 4.2.x

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
@simPod I tried merging up your commit, but it does not seem to work on 4.2.x, for Oracle. Did I do something wrong when resolving conflicts, or is it because of changes specific to this branch?

**Comment by simPod** [comment]
Just to be sure, you mean IBM, right?

image

**Comment by greg0ire** [comment]
Oh yeah sorry.

**Comment by simPod** [comment]
This is tmp fix [simPod/dbal@`f9681b3` (#11)](https://github.com/simPod/dbal/pull/11/commits/f9681b32794478cb39fdd04fa4ff641ae6c27c30)

TLDR transaction nesting is not working on DB2 now because of this

https://github.com/doctrine/dbal/blob/220aec46be990c0900826e29d9e3faa53bfbf70a/src/Connection.php#L1085

**Pull request merged**
