### PR TITLE
Warning: implode(): Invalid arguments passed in SimpleArrayType.php

### PR DESCRIPTION
**Pull request by JarJak**
Updated version of #2726

### CODE REVIEW

**Comment by Ocramius** [comment]
As much as I'd like this to be in every type, the added overhead is always a big issue, especially in types.

In addition to that, the type assumes that every value is stringable, yet this patch doesn't check for that.

The problem is exactly that: use a type checker like `phpstan/phpstan` and document your object properties accordingly, since runtime type checking is expensive (when not delegated to the engine), and it's a rabbit hole that is pretty much infinite.

**Comment by jvasseur** [comment]
Maybe we could use `assert` to add some runtime checks that could be disabled on production servers to remove the overhead.

**Comment by JarJak** [comment]
@jvasseur now it uses assert(), thanks for suggestion

**Comment by JarJak** [comment]
@morozov why closed?

**Pull request closed without merging**
