### PR TITLE
Revert full support for foreign key constraints for SQLite

### LINKED ISSUE #4243: SQLite Foreign Key Behavior BC Break
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.10.3

#### Summary

A change in SQLite foreign key constraint behavior is a breaking change that was released as a patch release.

See: https://github.com/laravel/framework/issues/34093

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no

Fixes #4243.

### CODE REVIEW

**Comment by morozov** [comment]
> ✗ pdo_oci Could not install pdo_oci on PHP 7.4.9

This failure is irrelevant. Looks like an issue with [shivammathur/setup-php](https://github.com/shivammathur/setup-php).

**Review by beberlei — DISMISSED** [review]

**Review by greg0ire — DISMISSED** [review]

**Comment by SenseException** [comment]
Are those failing tests for PostgreSQL in Travis also expected?

**Comment by morozov** [comment]
They started failing everywhere a few days ago (e.g. [#725359609](https://travis-ci.org/github/doctrine/dbal/builds/725359609)), so they are unrelated to this fix. But we need to take care of these tests before the release, so merging this revert can wait until then.

**Comment by morozov** [comment]
The failures must be the result of fixing bug [#64705](https://bugs.php.net/bug.php?id=64705) (https://github.com/php/php-src/commit/2fe2e5b48f8cf9a45ac2530dd0e2dca8f4287e01).

**Review by greg0ire — APPROVED** [review]

**Pull request merged**
