### PR TITLE
Added SET and ENUM types for MySQL and fix issue with schema update tool

### PR DESCRIPTION
**Pull request by dimak08**
Set and Enum data types are one of the most popular. However, addition of these data types in the project creates a problem when updating of the database structure.

### CODE REVIEW

**Comment by Ocramius** [comment]
This won't be implemented, sorry.

We only support portable functionality, and `SET` and `ENUM` are, honestly, a mess that we can't deal with in a cross-platform compliant way.

Also see http://stackoverflow.com/a/9057352/347063

**Comment by stof** [comment]
you should submit them to https://github.com/beberlei/DoctrineExtensions with other MySQL-specific stuffs (not sure whether the repo is still maintained though).

And I'm not sure this will work properly in the schema tool when inspecting enums or when comparing schemas btw

**Comment by Ocramius** [comment]
@dimak08 note that this is also a very old feature request that was marked as "won't fix" earlier too: http://www.doctrine-project.org/jira/browse/DBAL-4

**Comment by deeky666** [comment]
You could make it a commented type to allow the schema manager to recognize it.

**Comment by stof** [comment]
@deeky666 no you cannot. You can rely on commented types if you have a Doctrine type for ``ENUM('foo', 'bar')`` and a **different** Doctrine type for ``ENUM('foo', 'bar', 'baz')``. this is precisely what makes the ENUM type so painful

**Pull request closed without merging**
