### PR TITLE
MSSQL DLL 5.2.0 has been released.

### PR DESCRIPTION
**Pull request by photodude**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | was using the RC version of the MSSQL DLL

#### Summary

uses the release version rather than the outdated RC1 version

Release DLL info https://pecl.php.net/package-changelog.php?package=sqlsrv&release=5.2.0

### CODE REVIEW

**Comment by morozov** [comment]
@photodude please also update `tests/travis/install-mssql-*.sh`.

**Comment by photodude** [comment]
@morozov, unfortunately, I recently broke my desktop git install and I haven't been able to get it resorted and working correctly. My last attempt to rebase and squash majorly broke a PR I was working on. To be honest I have a bit of anxiety with dealing with git from that whole experience (I'm always nervous I'm going to screw it up as per XKCD commentary https://xkcd.com/1597/ ).

**Comment by morozov** [comment]
@photodude given that your commits are signed, I can neither squash them for you nor merge-squash. If I do that, you'll lose your signature on the commit. This is how I'd do that:
```
git reset --soft HEAD~2 # assuming you have 3 commits in total
git commit --amend
git push <wherever-you-push-your-changes> -f
```

**Comment by photodude** [comment]
I'm hoping I got this sorted and my git install is working correctly again. Although I think I ended up with something like vim in powershell. I was almost stuck in the escape room http://turnoff.us/geek/escape-room/

**Review by morozov — APPROVED** [review]
@photodude, congrats! I've restarted the failing build.

**Pull request merged**
