### PR TITLE
Use variadic instead of func_get_args

### PR DESCRIPTION
**Pull request by danizord**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | 

#### Summary

So that it can be proxied with ProxyManager.
See https://github.com/Ocramius/ProxyManager/issues/269

### CODE REVIEW

**Comment by danizord** [comment]
nvm, it would require a BC breaking change in `Connection` interface :/

**Comment by danizord** [comment]
Actually, it seems like PHP allows to add variadic arguments to the implementation even if the interface does not require any argument. So I'm reopening :)

**Comment by Majkl578** [comment]
This is still a BC break since PDOConnection is not final. However it may be fine for 3.x if you rebase & retarget to develop.

**Comment by morozov** [comment]
Closing this since it's not acceptable for `master` and is already solved in `develop` (#3080).

**Comment by gggeek** [comment]
It seems that this is still an issue when using ProxyManager 2.8.1 with DBAL 2.11.1, even though in that release Connection is not extending PDO any more...

**Pull request closed without merging**
