### PR TITLE
Manually merge 2.10.x into 2.11.x

### PR DESCRIPTION
**Pull request by greg0ire**
I did a little experiment in this merge up: instead of doing an evil merge, I did the required changes in a separate commit, but I move said commit before the merge, so that there is no commit that doesn't pass the build. That commit, which needs to be reviewed, is 12346644c

### CODE REVIEW

**Comment by morozov** [comment]
> I did a little experiment in this merge up: instead of doing an evil merge, I did the required changes in a separate commit, but I move said commit before the merge, so that there is no commit that doesn't pass the build.

I’ve been doing the same for some time as well: if a change that is needed for the merge build to pass can be made in the target branch prior to the merge, I'll make it there. Although, depending on the number of changes, conflicts, etc. this process may be quite non-straightforward. Any know-how from you @greg0ire?

**Review by morozov — APPROVED** [review]

**Comment by greg0ire** [comment]
> Any know-how from you @greg0ire?

Not really, I did the merge, fixed the issues, then rebased on 2.11.x and re-did the merge… feels a bit clumsy and might not work every time indeed, but glad to see we had the same idea :)

**Comment by morozov** [comment]
What I do is:

1. Do the merge, resolve conflicts, and make all the needed changes to make the build pass to in the merge commit.
2. Once I realize that some changes should be made prior to the merge, I make another clone of the repo (just by copying the project).
3. Switch back to the target branch and port all the needed changes from the merge commit.
4. Do the merge again but instead of resolving conflicts, just copy the entire tree from the clone.
5. Done.

In general, the clone and copy approach could be replaced with `git checkout <merge-sha> -- .` but it doesn't delete the files that should no longer exist in the tree. This is the clumsy part in my case..

**Comment by greg0ire** [comment]
I have the same issue with 3.0.x, so I will try again and pay more attention to see if `git rerere` kicks in… I think it didn't last time, but I'm not 100% sure. If it does, it should could help. If it doesn't that would be because the parent commit differ but I don't think that should be an issue for `git rerere`

**Comment by greg0ire** [comment]
It does kick in:

```
Resolved 'composer.lock' using previous resolution.
Resolved 'src/Connections/PrimaryReadReplicaConnection.php' using previous resolution.
Resolved 'src/Platforms/SQLServer2012Platform.php' using previous resolution.
```

**Comment by morozov** [comment]
Why do you need to re-resolve the same conflict more than once? Didn't this conflict exist between say 2.10 and 2.11 and it doesn't exist between 2.11 and 3.0?

**Comment by greg0ire** [comment]
I proceed like this:
1. merge and fix obvious conflicts
2. notice more things need to be fixed for Psalm to run cleanly
3. fix those and commit
4. rebase on the target branch, dropping everything but that last commit. At that point, I have lost the merge commit
5. run the merge again, run into the same conflict, let rerere resolve them

> Didn't this conflict exist between say 2.10 and 2.11 and it doesn't exist between 2.11 and 3.0?

The conflict is different that conflicts between 2.10 and 2.11 indeed

**Comment by morozov** [comment]
> run the merge again, run into the same conflict, let rerere resolve them

This is what I've been fixing just by copying the tree. By the time the same conflict happens again, I already know what the expected result is, regardless of whether `rerere` kicks in.

**Comment by greg0ire** [comment]
Might be better because `rerere` does not seem to record deletion, which I had to do again with `git mergetool`. That was done quickly, but still…

**Pull request merged**
