### PR TITLE
Remove underscores from private/protected members names

### PR DESCRIPTION
**Pull request by mateuszsip**
Closes https://github.com/doctrine/dbal/issues/3004

### CODE REVIEW

**Comment by Majkl578** [comment]
Restarted the failing build. Although not a blocker, can you please look into the CS issues? We currently have a rule that modified code should follow Doctrine CS (even if rest of the code doesn't yet).
We should also consider a BC layer for master in separate PR.
Otherwise 👍.

**Comment by morozov** [comment]
@Majkl578 I believe we could ignore the code style issues for massive automated changes like this as long as they don't introduce new issues.

What kind of a BC layer do you have in mind? For protected methods, we could have the deprecated old methods which invoke the new ones. But what about properties?

**Comment by Ocramius** [comment]
Benefits here are too marginal to consider the patch, compared to massive BC concerns. Closing as `won't fix`.

**Comment by Majkl578** [comment]
How about reconsidering what really needs to be protected and for those provide final protected getter (and make fields private)?

**Comment by Ocramius** [comment]
@Majkl578 anything that we can make `final` probably should be, but we should do that before considering any style changes. That is a design change :-)

**Comment by morozov** [comment]
Besides the above, we still can fix private methods and properties and protected methods and properties in the non-abstract test classes.

As for private/protected as such, there's also lack of consistency across the codebase. For instance, `MysqliConnection::_conn` if private but `OCI8Connection::dbh` is protected.

**Pull request closed without merging**
