### PR TITLE
Update AbstractPlatform.php

### PR DESCRIPTION
**Pull request by szekeresa**
trim $dbType

### CODE REVIEW

**Comment by deeky666** [comment]
Why is this necessary? Please explain the actual issue.

**Comment by deeky666** [comment]
@szekeresa ping

**Comment by szekeresa** [comment]
Hi!

I have sqlite database, but when the get schema then run out error:

```
DBALException in AbstractPlatform.php line 423:
Unknown database type nvarchar requested, Doctrine\DBAL\Platforms\SqlitePlatform may not support it.
in AbstractPlatform.php line 423
at AbstractPlatform->getDoctrineTypeMapping('nvarchar ') in SqliteSchemaManager.php line 288
at SqliteSchemaManager->_getPortableTableColumnDefinition(array('cid' => '3', 'name' => 'CimzettPartnerKod', 'type' => 'nvarchar (64)', 'notnull' => '0', 'dflt_value' => null, 'pk' => '0')) in AbstractSchemaManager.php line 820
```

Work around:
registerDoctrineTypeMapping(**'nvarchar '**, 'string'); // space in type name....


Other:
```
DBALException in AbstractPlatform.php line 423:
Unknown database type text requested, Doctrine\DBAL\Platforms\SqlitePlatform may not support it.
in AbstractPlatform.php line 423
at AbstractPlatform->getDoctrineTypeMapping('text ') in SqliteSchemaManager.php line 288
at SqliteSchemaManager->_getPortableTableColumnDefinition(array('cid' => '17', 'name' => 'Szolgaltatasok', 'type' => 'text (1073741823)', 'notnull' => '0', 'dflt_value' => null, 'pk' => '0')) in AbstractSchemaManager.php line 820
```

Work around:
registerDoctrineTypeMapping(**’text '**, 'string'); // space in type name....

In the database exists other nvarchar fileds, but not run error...

**Comment by deeky666** [comment]
@szekeresa found the issue. This can only occur if the underlying table was not created by DBAL and contains whitespaces in the column type declarations for string typed columns.

Provided a patch in #2272

**Pull request closed without merging**
