### PR TITLE
Consistent PHPUnit configuration across environments

### PR DESCRIPTION
**Pull request by morozov**
1. XSD location pointing to the vendored file.
2. Removed `backupGlobals="false"`.
3. Added `failOnRisky="true" failOnWarning="true"`.
4. Added code coverage whitelist.

### CODE REVIEW

**Comment by Majkl578** [comment]
What is the reason to remove `backupGlobals=false`?
Also beStrictAboutOutputDuringTests and beStrictAboutTodoAnnotatedTests are inconsistent accross configs.

**Comment by morozov** [comment]
> What is the reason to remove `backupGlobals=false`?

It's `false` by default according to the schema definition (PhpStorm highlights it as redundant).

> Also `beStrictAboutOutputDuringTests` and `beStrictAboutTodoAnnotatedTests` are inconsistent accross configs.

Let's update them too.

**Comment by Majkl578** [comment]
So PHPUnit's documentation is outdated probably, it shows `true`. :/ https://phpunit.readthedocs.io/en/latest/configuration.html

**Comment by morozov** [comment]
> So PHPUnit's documentation is outdated probably, it shows `true`. :/
> https://phpunit.readthedocs.io/en/latest/configuration.html

It is outdated: https://github.com/sebastianbergmann/phpunit/blob/536f4d853c12d8189963435088e8ff7c0daeab2e/src/Util/Configuration.php#L635-L640

**Comment by morozov** [comment]
@Majkl578 do you want to review this again?

**Review by Majkl578 — APPROVED** [review]

**Pull request merged**
