### PR TITLE
Manual merge of 2.10.x into 2.11.x

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by morozov** [comment]
No, I mean the up-merge and #3977.

**Comment by greg0ire** [comment]
Oh right, because it's a merge up of #3977 . I won't push it without also pushing #3977 itself though

**Comment by morozov** [comment]
Okay. Then should we merge #3977 first? Is it ready for review?

**Comment by greg0ire** [comment]
@morozov all 4 PRs are ready, don't merge any of them , just approve if they look ok. The plan is described in the TODO list

**Comment by greg0ire** [comment]
@morozov please approve this one (no additional commits here)

**Review by morozov — APPROVED** [review]

**Pull request merged**
