### PR TITLE
add `requiresSQLCommentHint` in `DateIntervalType`

### PR DESCRIPTION
**Pull request by vbartusevicius**
According to comment https://github.com/doctrine/dbal/pull/854#issuecomment-126935212

### CODE REVIEW

**Comment by deeky666** [comment]
@v-bartusevicius thanks for the addition. We need at least a unit test case for the newly added method. Also I would like to have the functional test suite extended to verify that the mapping is working correctly now. A test case should be added [here](https://github.com/doctrine/dbal/blob/master/tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php)

**Comment by v-bartusevicius** [comment]
@deeky666 - I did something here... not sure what as tests are skipped locally.
If You could provide me some more information on what You want me to extend in `DbalFunctionalTestCase` (or elsewhere), I would try to implement that.

**Comment by zeroedin-bill** [comment]
@v-bartusevicius I think he's referring to https://github.com/doctrine/dbal/blob/master/tests/Doctrine/Tests/DBAL/Functional/TypeConversionTest.php

**Comment by deeky666** [comment]
@v-bartusevicius merged manually with an additional test added. Thanks!

**Pull request merged**
