### PR TITLE
Allow dynamic intervals in DATE_ADD for SQLite

### PR DESCRIPTION
**Pull request by fogs**
Fixing #2983

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
Requires test additions

**Comment by fogs** [comment]
Can you give an example of additional tests required? I did not find tests for DATE_ADD at all.

**Comment by Ocramius** [comment]
https://github.com/doctrine/dbal/pull/2482 includes similar changes

**Comment by fogs** [comment]
@Ocramius,
What can I do to get this change merged? What type of tests would you like to see? Can you point me in the direction of already existing tests that I can reuse? I did not find anything but I have never contributed to a big project like this.

Thanks!

**Comment by Ocramius** [comment]
It doesn't matter if it's a big or small project: if an addition or change isn't backed by tests, it should not land in the codebase. This should be something that applies also for your own projects ;-)

As I've linked above, #2482 has similar tests - see https://github.com/vhraban/dbal/blob/d81e2a4e5937e045df4d79c8cad073d306c4abd6/tests/Doctrine/Tests/DBAL/Platforms/SqlitePlatformTest.php

**Comment by fogs** [comment]
Closing in favor of https://github.com/doctrine/dbal/pull/3019 which comes with the requested tests

**Pull request closed without merging**
