### PR TITLE
CS bump to 4.0, imports for global functions & constants

### PR DESCRIPTION
**Pull request by Majkl578**
CS is a simple bump (no change required since we use incremental diffs here).

Had to hack some sniffs to:
* only add imports for functions/constants (and not classes as well)
* to re-order only functions/constants (and not classes as well)

Would love to see this in 2.7, but not a dealbreaker.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
This is an easy and big win. It won't make a huge difference in this test suite alome, but things like the DBAL types are used a gazillion times, and we may have some improvements there 👍

**Comment by Ocramius** [comment]
Checked scrutinizer issues: mostly raised by non-existence of exotic extensions (db2, sql anywhere, sqlsrv)

**Comment by Bilge** [comment]
But why was `composer.lock` readded?

**Comment by Ocramius** [comment]
`composer.lock` is needed when testing with tools like phpcs, because they keep inadvertedly breaking BC.

We use `composer install` (with `composer.lock`) in some CI pipeline steps.

**Pull request merged**
