### PR TITLE
Merge 3.8.x up into 4.0.x

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
I'm not sure how to rewrite the tests from https://github.com/doctrine/dbal/commit/008a802fa17df91cb74a4953befe52643bf7d524 for 4.0.x @mvorisek , can you please advise?

**Comment by mvorisek** [comment]
@greg0ire I can fork your branch and look at it today evening.

**Comment by mvorisek** [comment]
Here is https://github.com/greg0ire/dbal/pull/7 PR to your branch with the fixes.

**Comment by greg0ire** [comment]
This URL seems to be having issues: https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz

> Please contact the server administrator at you@your.address to inform them of the time this error occurred, and the actions you performed just before this error.

Not sure that will work :stuck_out_tongue:

**Review by SenseException — APPROVED** [review]

**Pull request merged**
