### PR TITLE
Unset url parameter before logging parameters

### LINKED ISSUE #5339: Log message for database connection exposes the full URL that may contain plain text credentials
|    Q        |   A
|------------ | -----
| Version     | 3.3.4

The doctrine channel records the following log when a connection is established to the database:

```
Connecting with parameters array{
    "url":"postgresql://username:PLAIN_TEXT_PASSWORD@hostname/database_name",
    "driver":"pdo_pgsql",
    "host":"hostname",
    "port":null,
    "user":"username",
    "password":"<redacted>",
    "driverOptions":[],
    "serverVersion":"12",
    "defaultTableOptions":[],
    "dbname":"database_name",
    "charset":"utf8"
}
```
Although the `password` field value is not visible (`<redacted>` instead), the password is visible in the `url` field (https://github.com/doctrine/dbal/blob/3.3.x/src/Logging/Driver.php#L31). Using an URL instead of individual DB parameters is valid though (https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#getting-a-connection).

This can be a security issue regarding where the logs are stored and who has access to those logs.

### PR DESCRIPTION
**Pull request by greg0ire**
It will often contain a password. We could do more clever things like
redacted only the password part, but this seems hard to do in a robust
way.

|      Q       |   A
|------------- | -----------
| Type         | security
| Fixed issues | closes #5339

### CODE REVIEW

**Review by stof — APPROVED** [review]
Given that the logging parameters already contain the params extracted from the URL, this is fine to me.

**Comment by greg0ire** [comment]
Closing in favor of #5345

**Comment by stof** [comment]
@greg0ire you closed this PR in favor to itself. I think something is wrong in your comment

**Comment by greg0ire** [comment]
Fixed. Let me know what you think is the best solution, but maybe  it's good to know that it exists and was effectively passed to the driver, as opposed to thinking a bug removed it somehow

**Comment by greg0ire** [comment]
I'll assume you agree the other one is best given @derrabus approved it.

**Pull request closed without merging**
