### PR TITLE
Filter MySQL and Oracle columns by table type

### LINKED ISSUE #5579: MySQL: Schema Manager listTables() contains views
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.4.0

#### Summary

Since https://github.com/doctrine/dbal/commit/194c6eb7b78173fb8ae0ece8bc85be80d0364d89#diff-c2edb678105c04df1dd166e5a3553488b8084b7eca0cf34e8c0f96a512383fdd doctrine/dbal also list views as part of existing tables. I'm not sure how other platforms are affected by this change.

#### Current behaviour

The table information contains not only tables but also views.

#### How to reproduce

1. Create an database containing a view
2. Use `MySQLSchemaManager::listTables()`

#### Expected behaviour

The table list contains all tables but no views.

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | bug

Fixes #5579.

### CODE REVIEW

**Review by derrabus — DISMISSED** [review]

**Comment by morozov** [comment]
Sorry, there was a conflict in the test suite with #5586 🤷‍♂️

**Review by derrabus — APPROVED** [review]

**Comment by m-vo** [comment]
This change unfortunately introduced a severe performance hit. At least on MySQL 5.7 and MariaDB 10.6.

On a test database, querying the information schema columns took ~8ms and now (with the `INNER JOIN` on `information_schema.TABLES`) takes ~480ms, so over 50x more. 😕

Not sure what is going on here. The individual query of `information_schema.TABLES` is fast as well and replacing the join with a subquery (`WHERE TABLE_NAME IN (SELECT TABLE_NAME FROM information_schema.TABLES […])` restores the speed again.

This might be a MySQL/MariaDB issue in the first place, but we should IMHO take care of it in dbal nevertheless.

**Comment by morozov** [comment]
@m-vo thank you for the feedback. Do you mind filing a separate issue? IIRC, we dealt with some MySQL quirks regarding the performance of schema introspection recently. I'll try to look up the corresponding issue and see if this is something related.

**Comment by m-vo** [comment]
See #5638.

>  IIRC, we dealt with some MySQL quirks regarding the performance of schema introspection recently

Yeah, I vaguely remember something like this as well. :slightly_smiling_face:

**Pull request merged**
