### PR TITLE
Check column length for text type column

### PR DESCRIPTION
**Pull request by jewei**
For this issue, https://github.com/doctrine/dbal/issues/2566

### CODE REVIEW

**Comment by lcobucci** [comment]
@jewei I cannot see how the fix relates to the linked issue, can you please add tests that confirms the related problem?

**Comment by frandieguez** [comment]
Any news on getting this integrated?

**Comment by Ocramius** [comment]
A test case is required in order to consider this patch.

**Comment by morozov** [comment]
Closing as stale and missing tests. This will be likely resolved by https://github.com/doctrine/dbal/pull/4659.

**Pull request closed without merging**
