### PR TITLE
Don't use null as exception message

### PR DESCRIPTION
**Pull request by derrabus**
|      Q       |   A
|------------- | -----------
| Type         | bug
| BC Break     | no
| Fixed issues | N/A

#### Summary

`null` is not a valid exception message. Before PHP 8.0, `null` was silently cast to an empty string. On PHP 8.1 however, passing `null` as `$message` to `Exception__construct()` will trigger  a deprecation warning.

This PR proposes to change the tests so that the empty string is used instead of `null`.

### CODE REVIEW

**Comment by SenseException** [comment]
The values for `$message` are all the same. Is it necessary to keep them in the data provider?

**Comment by derrabus** [comment]
There is also one data provider that emits actual error messages.

**Comment by morozov** [comment]
Note, these changes are likely already implemented in newer branches. But as I said earlier, I do not think we should be implementing the support for PHP 8.1 in DBAL 2.x.

**Comment by derrabus** [comment]
See my comment https://github.com/doctrine/dbal/pull/4734#issuecomment-889822586

Let's continue the discussion there.

**Review by morozov — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @derrabus !

**Pull request merged**
