### PR TITLE
Manually merge 2.11.x into 3.0.x

### PR DESCRIPTION
**Pull request by greg0ire**
Conflicts in psalm.xml and composer.json, baseline changed

### CODE REVIEW

**Comment by morozov** [comment]
@greg0ire please try force-pushing or otherwise file a new PR. Since this one was opened against `2.10.x` ContinuousPHP was trying to use its build configuration and failed.

**Comment by greg0ire** [comment]
Ok, sorry for the mess.

**Comment by greg0ire** [comment]
Argh now Appveyor is suffering from 503, let's try again.

**Comment by greg0ire** [comment]
Ok let's try again when this page is green: https://status.chocolatey.org/

**Review by morozov — APPROVED** [review]

**Pull request merged**
