### PR TITLE
Ci no upload.x

### PR DESCRIPTION
**Pull request by grooverdan**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| Fixed issues | 

#### Summary

Allow CI to run in forked repos without failing on this explicit `doctrine/dbal` part of the github action workflows.

### CODE REVIEW

**Comment by grooverdan** [comment]
helps if I have a non-failing CI to demonstrate this: https://github.com/grooverdan/dbal/actions/runs/9413683501

**Comment by greg0ire** [comment]
The codecov upload sometimes works and is not a required check. When it works, it allows us to check that the patch is covered. I would leave things as is.

**Comment by derrabus** [comment]
But should the CodeCov upload run on forks as well?

**Comment by greg0ire** [comment]
Yes. And it very often does, check other PRs

**Comment by derrabus** [comment]
All right.

**Pull request closed without merging**
