### PR TITLE
Missing type hints in $query, $params, $types sets

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Looking good from here, although unsure if this will be a BC break (too little :coffee: and toi early in the morning)

**Comment by Majkl578** [comment]
Wouldn't pursue similar changes until develop lands in master, too early in the DBAL 3.0 cycle.
Otherwise needs rebase and fixing CS.

**Review by Majkl578 — CHANGES_REQUESTED** [review]
I still think we shouldn't do this until develop is merged into master. (Same as fixing CS globally.)

**Comment by ostrolucky** [comment]
superseded with https://github.com/doctrine/dbal/pull/3348

**Pull request closed without merging**
