### PR TITLE
Connection::ping() will return void

### PR DESCRIPTION
**Pull request by morozov**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | yes

As suggested in https://github.com/doctrine/dbal/pull/3348#discussion_r236016744.

### CODE REVIEW

**Comment by Ocramius** [comment]
The unhappy path could be tested if we were able to cut the connection to the DB. For PDO, we could mock the PDO instance itself. For drivers relying on global functions, it would require us to bring down the real DB connection.

I'd say that if the PDO testing is possible, we should at least try that.

**Comment by morozov** [comment]
Can't inject `PDO` on `develop` due to #3487.

**Comment by morozov** [comment]
Testing the happy path with PDO is no longer possible as of #3548. The fact that it takes us that long to come up with a testing approach makes me question the need for this API even more:

> Given that only MySQL implements it natively, what's the value of the specialized API?

@Ocramius, in the interest of making progress with enforcing types, I think we should just merge it as is.

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
@morozov :ship:

**Pull request merged**
