### PR TITLE
Document MySQL error codes

### PR DESCRIPTION
**Pull request by BenMorel**
|      Q       |   A
|------------- | -----------
| Type         | improvement
| BC Break     | no
| Fixed issues | none

#### Summary

Documents mysql error codes for easier reading.

References:

- https://dev.mysql.com/doc/refman/5.7/en/server-error-reference.html
- https://dev.mysql.com/doc/refman/5.7/en/client-error-reference.html

### CODE REVIEW

**Comment by BenMorel** [comment]
Not sure how to fix the `phpcs` issue:

- when I don't put an empty line before the `return` statement, I get:

> Expected 1 lines before "return", found 0.

- when I do put an empty line before it, I get:

> The CASE body must start on the line following the statement

This contradiction only occurs when a comment is on the same line as the `case`.

**Comment by morozov** [comment]
Why not define the codes as constants instead of comments?

**Comment by BenMorel** [comment]
It's a possibility, it just adds a bit of burden for something that's not going to be reused anywhere IMHO.

If you wish to proceed this way, please tell me where they should go:

- as constants in the `AbstractMySQLDriver` class
- or as constants in the `Doctrine\DBAL\Driver` namespace (and in which file then?)

**Comment by lcobucci** [comment]
@BenMorel I'd suggest private constants in `AbstractMySQLDriver`.

**Comment by BenMorel** [comment]
Here you are!

**Comment by morozov** [comment]
> It's a possibility, it just adds a bit of burden for something that's not going to be reused anywhere IMHO.

It's not about reuse. It's about self-documenting code.

> Here you are!

Thank you.

Could you please also move the `@link` annotations from `convertException()` to the group block around the newly declared constants like here?
https://github.com/doctrine/dbal/blob/c104c687f6a3880fb9ddeb5f9ebc4fae11d12466/lib/Doctrine/DBAL/SQLParserUtils.php#L34-L42

And then squash.

**Comment by BenMorel** [comment]
Is this `/**#@+ ... */ ... /**#@-*/` a PHPdoc standard of some sort? I've never come across this one.

**Comment by morozov** [comment]
> Is this `/**#@+ ... */ ... /**#@-*/` a PHPdoc standard of some sort? I've never come across this one.

This is/was actively used in [PEAR](https://github.com/pear/pear-core/blob/9e9014d4aa662db336eef3121011bdcd27f5e63f/PEAR.php#L21-L34), also I'm not sure if it's part of the phpDoc standard.

**Comment by BenMorel** [comment]
@morozov All done!

**Review by morozov — APPROVED** [review]

**Comment by morozov** [comment]
Thanks @BenMorel! :ship:

**Pull request merged**
