### PR TITLE
Fix list foreign keys SQL database parameter evaluation

### PR DESCRIPTION
**Pull request by deeky666**
See https://github.com/doctrine/dbal/commit/e24444e86ef06223f2f477fb836c08c9cc27f619#commitcomment-15340913

### CODE REVIEW

**Comment by kimhemsoe** [comment]
Looks good

**Comment by deeky666** [comment]
@Ocramius need another scary green-button-action :>

**Comment by Ocramius** [comment]
Green button said yes!

**Comment by Ocramius** [comment]
Backported into `2.5` via doctrine/dbal@bc85f1424b43158fdffecca8e339aaa6498b8251

**Pull request merged**
