### PR TITLE
Fixed camel case in method name.

### PR DESCRIPTION
**Pull request by zomberg**

### CODE REVIEW

**Review by phansys — CHANGES_REQUESTED** [review]
:-1: [`Column::setNotnull()`](https://github.com/doctrine/dbal/blob/ba4561f74feb4f8060f0eb9de77daac5e1a901ce/lib/Doctrine/DBAL/Schema/Column.php#L218) doesn't match the requested change.

**Review by phansys — COMMENTED** [review]
Sorry for my previous negative vote, I didn't noticed that you was updating the method definition too. Just for consistency, IMO, the argument (`$notnull`) and the property (`$_notnull`) cases can be updated too.

**Comment by Ocramius** [comment]
Indeed, please update the argument as well :-) The property cannot be changed though, as it is protected API, and we don't know if anybody is using `get_object_vars()` in a subclass.

**Comment by zomberg** [comment]
Sorry, I can't fix this because earlier I removed my fork for this repository.

**Comment by Ocramius** [comment]
Closing as incomplete then.

**Pull request closed without merging**
