### PR TITLE
feat: support value extraction from enum on `Statement::bindValue()`

### PR DESCRIPTION
**Pull request by simPod**
|      Q       |   A
|------------- | -----------
| Type         | feature

#### Summary

I thought it would be nice to auto extract value from enum.

### CODE REVIEW

**Review by derrabus — CHANGES_REQUESTED** [review]
I don't think we should guess how a non-scalar value should be represented in the database. This kind of functionality should be implemented outside of DBAL, e.g. in the ORM.

**Comment by simPod** [comment]
I use it with dbal. My problem is that when I bind parameters to a statement of enum type, I always have to access `->value`.

Do you think there can be cases where this is not desired?

**Comment by derrabus** [comment]
> Do you think there can be cases where this is not desired?

Yes, for the same reasons why we don't automagically convert `DateTime` objects for instance. The connection class is a low-level database API that intentionally does not guess conversion rules for passed values. We should really keep it as simple as possible.

The DBAL has a type system for that purpose and you could leverage that for your enum.

**Comment by derrabus** [comment]
Closing as explained. Thank you for your proposal though.

**Comment by simPod** [comment]
Thank you as well.

**Pull request closed without merging**
