### PR TITLE
[DBAL-1137] Fix infinite recursion on non-unique table/join alias in QueryBuilder

### PR DESCRIPTION
**Pull request by JarJak**
What do you guys think about this solution? I found this problem when got not unique join alias - getSQLForJoins went for infinite recursion and apache crashed without promt..

### CODE REVIEW

**Comment by Ocramius** [comment]
@jarekj requires a test case

**Comment by jarekj** [comment]
here it is: https://github.com/doctrine/dbal/pull/791

**Comment by deeky666** [comment]
@jarekj the next time please just add your test to the existing PR by committing and pushing to the same branch again.

**Comment by jarekj** [comment]
@derky666 this test just shows that the problem exists, running this test in my fix branch I get:
Fatal error: Method Doctrine\DBAL\Query\QueryBuilder::__toString() must not throw an exception

**Comment by stof** [comment]
@jarekj and this shows you that your PR is wrong, which is actually a good thing too

**Comment by deeky666** [comment]
@stof not really. In his PR he already fixed the recursion issue by throwing an exception which would explain the error message he gets...

**Comment by stof** [comment]
@deeky666 but the exception is thrown in the wrong place, as throwing it inside ``__toString`` triggers a PHP Fatal Error. ``__toString`` is not allowed to throw exceptions in PHP

**Comment by deeky666** [comment]
@stof you are right. But the QueryBuilder also throws other exceptions in `__toString()` / `getSQL()` I'm not even sure why one would use `__toString()` to generate the SQL from the QueryBuilder anyways. Always found that weird...

**Comment by stof** [comment]
@deeky666 I also find it weird, and it should probably be removed in 3.0

**Comment by jarekj** [comment]
test fails for some unrelated reason i think

**Comment by deeky666** [comment]
@jarekj merged manually with some fixes and additions. Thanks!

**Comment by jarekj** [comment]
I am not sure this is right solution, I have tested it locally and found some false positives

**Comment by deeky666** [comment]
@jarekj what do you mean exactly by "false positives"? The test suite runs fine. Anything we have missed?

**Comment by jarekj** [comment]
Maybe we don't have enough tests written...

**Comment by deeky666** [comment]
Feel free to provide failing test cases in another PR if you have any.

**Comment by jarekj** [comment]
I am not sure what $knownAliases array is for - it could be changed to count aliases and throw the Exception when any alias comes more than once.

**Comment by jarekj** [comment]
@deeky666 see https://github.com/doctrine/dbal/pull/794 for more tests and throw exception in another place

**Pull request merged**
