### PR TITLE
Remove useless ternary in the `DecimalType`

### PR DESCRIPTION
**Pull request by ghost**
see https://github.com/doctrine/doctrine2/pull/1104#issuecomment-51755834
Thanks to @stof

### CODE REVIEW

**Comment by Ocramius** [comment]
```php
if ($val === true) {
    return true;
} elseif ($val === false) {
    return false;
} else {
    return $val;
}
```

#facepalm 

Thanks for sending the patch, @JHGitty!

**Comment by JHGitty** [comment]
@Ocramius As I understand this fix could also be merged to 2.1, 2.2, 2.3, 2.4 and 2.5
because it is just a minor code improvement. Are these versions still supported and should get this fix?

**Comment by Ocramius** [comment]
@JHGitty anything that isn't an actual bugfix won't make it into stable versions

**Comment by JHGitty** [comment]
@Ocramius Okay. Thanks :+1:

**Comment by deeky666** [comment]
lol crying tears over here :D thanks @JHGitty @Ocramius

**Pull request merged**
