### PR TITLE
getSQLForJoins - infinite recursion if join alias is not unique

### PR DESCRIPTION
**Pull request by JarJak**
fix for exception message

### CODE REVIEW

**Comment by Ocramius** [comment]
Requires a test case, IMO

**Comment by jarekj** [comment]
it just fixes exception message from my previous pull request, values of this array are all booean true

**Comment by Ocramius** [comment]
Yes, but a test verifies the fix and prevents a regression later on.

**Comment by deeky666** [comment]
I already applied that fix here https://github.com/doctrine/dbal/commit/7fec259f3fdfa86f3c5441b2583bd8c1a3f1d69a while merging your last PR.

**Comment by jarekj** [comment]
Thanks @deeky666 but I'm still not sure this is the best solution. I've got false positive in my project. I'll try to prepare test case that wiould produce it too.

**Comment by jarekj** [comment]
@deeky666 OK I got it. I was not false positive, I was doing something like:
$qb->from('table_a', 'a')->from('table_a', 'a')->from('table_a', 'a')->join('a', 'table_b', 'b')
Then it throwed the exception, which is quite accurate:
The given alias 'a' is not unique in FROM and JOIN clause table. The currently registered aliases are: a, b.
I can create test case for it.

**Pull request closed without merging**
