### PR TITLE
Use a template for Connection

### PR DESCRIPTION
**Pull request by greg0ire**
It is fair to say we connect to a platform, and this should provide
insights for static analysis, and make some assertions redundant.

### CODE REVIEW

**Comment by morozov** [comment]
@greg0ire FWIW I started a similar effort some time ago: https://github.com/doctrine/dbal/compare/3.4.x...morozov:generic-types. It looks like you're doing the same.

**Comment by greg0ire** [comment]
Thanks for the heads up @morozov ! I guess #5211 made you realize the piece of code I removed could have been detected as useless if we had that templating? Anyway, I'll let you do the honors, you've gone further than I did :slightly_smiling_face:

**Comment by morozov** [comment]
> I guess #5211 made you realize the piece of code I removed could have been detected as useless if we had that templating?

I started it during some other work a few months ago. I don't remember what it was.

> Anyway, I'll let you do the honors, you've gone further than I did 🙂

Actually, I don't mind if you manage to finish that. I got stuck somewhere at the wrapper `Connection` level. If you get through the cascade of errors and end up in a stable state, please feel free to use and contribute my patch. I just wanted to share it with so that you don't repeat the same work.

**Comment by greg0ire** [comment]
Ok, I'll give it another try then 👍

**Pull request closed without merging**
